//! Rendering one module's documentation.
//!
//! Markdown is emitted in a lint-clean style — padded table pipes, no blank
//! lines inside blockquotes — so the output does not itself become a source of
//! CI failures.

use super::model::Module;
use std::fmt::Write;

/// Banner on every generated file.
///
/// Present because the alternative is somebody editing a file that is
/// overwritten on the next run and losing the work without warning.
const BANNER: &str = "<!-- Generated by `cargo xtask protodoc`. Do not edit. -->";

/// Render one module's README.
pub fn module_readme(module: &Module) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}\n");
    let _ = writeln!(out, "# {}\n", module.name);
    let _ = writeln!(out, "**Package** `{}`\n", module.package);

    render_services(&mut out, module);
    render_messages(&mut out, module);
    render_enums(&mut out, module);

    out
}

fn render_services(out: &mut String, module: &Module) {
    if module.services.is_empty() {
        return;
    }
    let _ = writeln!(out, "## Services\n");

    for service in &module.services {
        let _ = writeln!(out, "### `{}`\n", service.name);
        if !service.comment.is_empty() {
            let _ = writeln!(out, "{}\n", service.comment);
        }
        if service.rpcs.is_empty() {
            continue;
        }

        let _ = writeln!(out, "| Method | Request | Response | Description |");
        let _ = writeln!(out, "| --- | --- | --- | --- |");
        for rpc in &service.rpcs {
            let response = if rpc.server_stream {
                format!("stream `{}`", rpc.response)
            } else {
                format!("`{}`", rpc.response)
            };
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} |",
                rpc.name,
                rpc.request,
                response,
                escape(&rpc.comment)
            );
        }
        let _ = writeln!(out);
    }
}

fn render_messages(out: &mut String, module: &Module) {
    if module.messages.is_empty() {
        return;
    }
    let _ = writeln!(out, "## Messages\n");

    for message in &module.messages {
        let _ = writeln!(out, "### `{}`\n", message.name);
        if !message.comment.is_empty() {
            let _ = writeln!(out, "{}\n", message.comment);
        }
        if message.fields.is_empty() {
            let _ = writeln!(out, "_No fields._\n");
            continue;
        }

        let _ = writeln!(out, "| Field | Type | # | Behavior | Description |");
        let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
        for field in &message.fields {
            let behavior = if field.behavior.is_empty() {
                String::new()
            } else {
                format!("`{}`", field.behavior)
            };
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} | {} |",
                field.name,
                field.type_name,
                field.number,
                behavior,
                escape(&field.comment)
            );
        }
        let _ = writeln!(out);
    }
}

fn render_enums(out: &mut String, module: &Module) {
    if module.enums.is_empty() {
        return;
    }
    let _ = writeln!(out, "## Enums\n");

    for value in &module.enums {
        let _ = writeln!(out, "### `{}`\n", value.name);
        if !value.comment.is_empty() {
            let _ = writeln!(out, "{}\n", value.comment);
        }
        let _ = writeln!(out, "| Value | # | Description |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for variant in &value.values {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} |",
                variant.name,
                variant.number,
                escape(&variant.comment)
            );
        }
        let _ = writeln!(out);
    }
}

/// Make text safe inside a Markdown table cell.
///
/// A pipe would silently split the row into extra columns, which renders as a
/// broken table rather than an error — so it is escaped rather than trusted.
fn escape(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
#[path = "render_test.rs"]
mod tests;
