//! The top-level summary and the module import graph.

use super::model::Module;
use std::fmt::Write;

const BANNER: &str = "<!-- Generated by `cargo xtask protodoc`. Do not edit. -->";

/// Render the root README covering every module.
pub fn root_readme(modules: &[Module], root_prefix: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}\n");
    let _ = writeln!(out, "# Protobuf API\n");
    let _ = writeln!(
        out,
        "One package per resource, each in its own versioned directory. Files \
         within a package are split by role: the resource, its request and \
         response messages, and its service.\n"
    );

    let _ = writeln!(out, "| Module | Package | Services | Messages | Enums |");
    let _ = writeln!(out, "| --- | --- | ---: | ---: | ---: |");
    for module in modules {
        let _ = writeln!(
            out,
            "| [{}]({}/README.md) | `{}` | {} | {} | {} |",
            module.name,
            module.dir,
            module.package,
            module.services.len(),
            module.messages.len(),
            module.enums.len()
        );
    }
    let _ = writeln!(out);

    render_graph(&mut out, modules, root_prefix);
    out
}

/// Draw the local import relationships between modules.
///
/// Only edges between modules in this repository are drawn. An arrow from every
/// node to `google.protobuf` would be true and useless — the graph exists to
/// show which resources depend on which, and a dependency everything shares
/// carries no information.
fn render_graph(out: &mut String, modules: &[Module], root_prefix: &str) {
    let edges: Vec<(String, String)> = modules
        .iter()
        .flat_map(|m| {
            m.local_imports(root_prefix)
                .into_iter()
                .map(move |dep| (m.short_name(), dep))
        })
        .collect();

    if edges.is_empty() {
        return;
    }

    let _ = writeln!(out, "## Module dependencies\n");
    let _ = writeln!(out, "```mermaid");
    let _ = writeln!(out, "graph LR");
    for module in modules {
        let _ = writeln!(
            out,
            "    {}[\"{}\"]",
            sanitize(&module.short_name()),
            module.name
        );
    }
    for (from, to) in edges {
        let _ = writeln!(out, "    {} --> {}", sanitize(&from), sanitize(&to));
    }
    let _ = writeln!(out, "```\n");
}

/// Mermaid node ids may not contain punctuation that would end the identifier.
fn sanitize(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

#[cfg(test)]
#[path = "summary_test.rs"]
mod tests;
