@0xfa5016ba603833d0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/system/v1/system_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::system::v1");

using System = import "/telividb/system/v1/system.capnp";

# Request message for retrieving the system singleton.
struct GetSystemRequest @0xe27500323fab6012 {
  # Resource name of the singleton. Always `system`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Reports what only this process can know about itself.
#
# Telemetry here emits shape, never values — `dimensions=768`, never the
# components. A vector in a log is readable by anyone with log access and can
# be inverted back toward its source text.
interface SystemInfo @0xf34c11de92d8937b {
  # Retrieves the selected backend, the device, and the memory budget.
  # AIP-131 standard method.
  getSystem @0 (request :GetSystemRequest) -> (response :System.System);
}
