@0xa4edae12e1aeddbb;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/system/v1/system.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::system::v1");

# How the device memory ceiling was determined.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum BudgetSource @0xed2ef55f21a9817f {
  # Default value. Never valid in a response.
  unspecified @0;
  # Read from the device.
  measured @1;
  # Inferred, because the backend reports no ceiling.
  estimated @2;
  # Set by configuration, overriding whatever the device reports.
  configured @3;
}

# Runtime facts an orchestrator cannot observe from outside the process.
#
# Deliberately small. Liveness, restarts, CPU and memory limits and GPU
# allocation are all things a scheduler already does better than a database
# can. What remains is what only this process knows — and the most important
# of it is which backend was actually selected, because a build that quietly
# fell back to the CPU passes every correctness test while delivering none of
# the speed. From outside, that failure is invisible: the pod is healthy, the
# GPU is allocated, and nothing is using it.
struct System @0xa99d82a69d3456b3 {
  # Resource name of the singleton. Always `system`.
  name @0 :Text;
  # Compute backend actually in use, such as `metal` or `cpu`.
  backend @1 :Text;
  # Human-readable device description.
  device @2 :Text;
  # Device memory ceiling this process will use.
  budgetLimitBytes @3 :Int64;
  # Device memory currently held by resident models and indexes.
  budgetUsedBytes @4 :Int64;
  # Whether the ceiling was measured or estimated.
  #
  # An estimate on a discrete card overshoots, and an operator sizing a
  # deployment has to be able to tell which number they are looking at.
  budgetSource @5 :BudgetSource;
  # Version of this build.
  version @6 :Text;
}
