//! The documentation header emitted into the generated `lib.rs`.
//!
//! Kept apart from the orchestration so neither file has to be read to
//! understand the other, and so a wording change is a diff in one place.

/// Module docs and lint attributes prepended to the generated `lib.rs`.
///
/// Carries the `@generated` marker on its first line, which is what excuses the
/// file from the length and doc-coverage checks — it is machine-written, and a
/// module list that must track 67 generated files has no business being
/// maintained by hand.
pub const PREAMBLE: &str = r#"// @generated by `cargo xtask gen-buffers`. DO NOT EDIT.
//! Cap'n Proto and FlatBuffers views of the protobuf schema of record.
//!
//! # Generated, not built
//!
//! Everything here is produced from `buffers/protobuf/` — by `buf` for the
//! protobuf views, by `buffers` for the flat ones — and **committed**. So
//! `cargo build` needs no protobuf toolchain, no `capnp` and no `flatc`: a
//! contributor clones and builds with rustup alone.
//!
//! # One crate, one schema, three renderings
//!
//! Protobuf, Cap'n Proto and FlatBuffers are not three schemas that happen to
//! agree — they are one schema rendered three ways, with `buffers.lock` keeping
//! a field in the same slot across numbering schemes that do not correspond.
//! Splitting them across crates would have invited them to drift.
//!
//! Regenerate with `cargo xtask gen-buffers`; CI runs `check-buffers` and fails
//! if the committed output has drifted from the protos.
//!
//! # One module per format, and why the private layer exists
//!
//! Callers reach these as [`capnp`] and [`flatbuffers`], and a third format
//! would be a third module beside them. That grouping is not what the
//! generators produce, though, and the gap is worth understanding before anyone
//! tries to tidy it away.
//!
//! Both `capnpc-rust` and `flatc` emit code that addresses its siblings
//! absolutely — `crate::message_capnp`, `crate::wellknown_generated` — so every
//! generated module must exist at the crate root or the generated code stops
//! compiling. Nesting them under `capnp::` would mean editing generated files,
//! which is the one thing a generated tree must never require.
//!
//! So the roots stay where the generators expect them, hidden from the docs,
//! and each format re-exports its own through a facade. Files live in
//! `generated/<format>/`, the public API is grouped by format, and not one
//! generated line is touched.
//!
//! The two sets coexist only because the `_capnp` and `_generated` suffixes
//! keep them disjoint. A third format must carry its own suffix for the same
//! reason.
//!
//! # FlatBuffers is opt-in, and the reason is `unsafe`
//!
//! FlatBuffers reads a field by pointing at bytes and trusting the layout, so
//! its generated accessors are `unsafe` by construction. Cap'n Proto validates
//! as it reads and generates none.
//!
//! Every crate here outside a short sanctioned list carries
//! `forbid(unsafe_code)`, and that containment is worth more than the
//! convenience of a default feature — so `unsafe` is forbidden unless the
//! `flatbuffers` feature is on, the same quarantine the optional FAISS index
//! gets rather than admission to the default build.
//!
//! Turn it on when something actually wires the FlatBuffers path: a contiguous
//! single-buffer layout is what a one-sided RDMA write wants, and that is the
//! case worth paying the `unsafe` for.
#![cfg_attr(not(feature = "flatbuffers"), forbid(unsafe_code))]
// `dead_code` joins the list because a generator emits a complete surface
// whether or not this build reaches all of it: each MCP server defines its own
// tool constructor, and a binary that serves one service still compiles the
// other thirteen.
#![allow(dead_code, missing_docs, clippy::all, rustdoc::all)]
"#;
