@0x9b127b7d27301ea5;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/tenancy/v1/organization.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::tenancy::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# The top of the tenancy tree, and the only container that never changes for
# anything beneath it.
#
# That permanence is why it is the one container that appears in a resource
# name: a conversation moves freely between projects and spaces, so encoding
# those in its name would make every move a rename and break every stored
# reference to it. Moving between organizations is an export, not a move.
#
# An organization is also the physical boundary. One organization is one
# collection, so purging a tenant never rewrites another tenant's segments.
struct Organization @0xd58fd897fb7cabb3 {
  # Resource name of the organization.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # Projects belonging to this organization.
  projectCount @2 :Int32;
  # Spaces belonging to this organization.
  spaceCount @3 :Int32;
  # When the organization was created.
  createTime @4 :Wellknown.Timestamp;
  # When the organization was last modified.
  updateTime @5 :Wellknown.Timestamp;
  # When the organization was soft-deleted, or unset while it is live.
  #
  # Deletion is reversible until `expire_time`. Nothing is physically removed
  # at delete: the tenant is tombstoned so queries exclude it immediately, and
  # compaction reclaims the bytes later.
  deleteTime @6 :Wellknown.Timestamp;
  # When a soft-deleted organization is purged and becomes unrecoverable.
  expireTime @7 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @8 :Text;
}
