@0xc48e35e342925be0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/tenancy/v1/project.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::tenancy::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A unit of work within an organization, and the unit at which access is
# granted.
#
# A project is a *predicate*, not a collection. At the scale this is designed
# for — organizations holding hundreds of projects each — a collection per
# project would mean thousands of manifests and thousands of graph indexes,
# most over a handful of conversations. Project membership compiles into the
# visibility bitmap instead, which is resolved once per query.
struct Project @0xc3a8c392a15932fb {
  # Resource name of the project.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # When the project was created.
  createTime @2 :Wellknown.Timestamp;
  # When the project was last modified.
  updateTime @3 :Wellknown.Timestamp;
  # When the project was soft-deleted, or unset while it is live.
  deleteTime @4 :Wellknown.Timestamp;
  # When a soft-deleted project is purged and becomes unrecoverable.
  expireTime @5 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @6 :Text;
}
