@0xb33b416ddbdc2594;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/tenancy/v1/session.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::tenancy::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A recorded working period holding several conversations.
#
# A session is a resource rather than a traversal result because it has its
# own identity, its own span, and its own summaries. "The conversations I had
# on Tuesday about the merger" is a thing a person names and returns to, and
# deriving it from edge ordering every time would lose the name.
struct Session @0xf924c87681786c52 {
  # Resource name of the session.
  name @0 :Text;
  # Human-readable name.
  displayName @1 :Text;
  # Space this session belongs to.
  #
  # Mutable, and therefore a field rather than a path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  space @2 :Text;
  # When the working period began.
  startTime @3 :Wellknown.Timestamp;
  # When the working period ended, or unset while it is still open.
  endTime @4 :Wellknown.Timestamp;
  # Conversations recorded in this session.
  conversationCount @5 :Int32;
  # When the session was created.
  createTime @6 :Wellknown.Timestamp;
  # When the session was last modified.
  updateTime @7 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @8 :Text;
  # When the session was soft-deleted, or unset while it is live.
  #
  # Present for the same reason it is on every other resource in this tree:
  # `DeleteSession` returns the tombstoned session, and without these there is
  # nowhere for it to say that it is one. A delete that returned a resource
  # indistinguishable from a live one would make `Undelete` unusable — a caller
  # could not tell what needed restoring.
  deleteTime @9 :Wellknown.Timestamp;
  # When a soft-deleted session is purged and becomes unrecoverable.
  expireTime @10 :Wellknown.Timestamp;
}
