@0xcba3688996444526;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/tenancy/v1/space.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::tenancy::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# What actually protects the contents of a space.
#
# The distinction is load-bearing rather than descriptive: only the last two
# involve cryptography, and calling an access-controlled space a vault would
# invite the assumption that it survives a compromised server.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Protection @0x83ec98a2750108f8 {
  # Default value. Never valid in a request.
  unspecified @0;
  # Visible according to ordinary role grants on the containing projects.
  none @1;
  # Readable only by its owner, enforced by a visibility predicate.
  #
  # Access control, not cryptography. Anyone who compromises the server reads
  # it, which is exactly why it is not called a vault.
  private @2;
  # Encrypted with a key the server wraps and holds.
  #
  # Contents live in their own segments so unlocking decrypts a region rather
  # than a row at a time.
  vault @3;
  # Encrypted with a key only the client holds.
  #
  # The server cannot read the contents even when compromised, and cannot
  # search them while locked.
  sealed @4;
}

# A named container for related conversation — a finance space, an education
# space, a private thread with one other person.
#
# A space is the unit at which protection is declared, and that is deliberate
# rather than incidental: an encrypted space needs its own segments so a whole
# region decrypts at unlock. Declaring protection per conversation would force
# per-row decryption and destroy the zero-copy read path.
struct Space @0xe0f3651b834d5ea7 {
  # Resource name of the space.
  name @0 :Text;
  # Human-readable name, such as `Finance`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # Projects this space belongs to.
  #
  # Repeated, and mutable: a space may span projects, and membership is not
  # encoded in the resource name precisely so it can change without renaming
  # anything that refers to this space.
  projects @2 :List(Text);
  # How the contents of this space are protected.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  protection @3 :Protection;
  # Whether the space is currently readable.
  #
  # A key-wrapped space that has not been unlocked is reported rather than
  # silently skipped: a search that could not read it sets `complete` to false
  # and names it, so a caller can tell "no results" from "no results you can
  # currently see".
  locked @4 :Bool;
  # When the space was created.
  createTime @5 :Wellknown.Timestamp;
  # When the space was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # When the space was soft-deleted, or unset while it is live.
  deleteTime @7 :Wellknown.Timestamp;
  # When a soft-deleted space is purged and becomes unrecoverable.
  expireTime @8 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @9 :Text;
}
