@0xd745f50527bfe5ea;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/tenancy/v1/tenancy_messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::tenancy::v1");

using Organization = import "/telividb/tenancy/v1/organization.capnp";
using Project = import "/telividb/tenancy/v1/project.capnp";
using Session = import "/telividb/tenancy/v1/session.capnp";
using Space = import "/telividb/tenancy/v1/space.capnp";

# Request message for creating an organization.
struct CreateOrganizationRequest @0xb5bb060abaef892e {
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  organizationId @0 :Text;
  # The organization to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  organization @1 :Organization.Organization;
  # Unique identifier making this request safe to retry.
  #
  # A create that times out and is retried without one writes the resource
  # twice, which for a tenant root is expensive to unpick.
  requestId @2 :Text;
}

# Request message for retrieving an organization.
struct GetOrganizationRequest @0x98fed3e9009f8d70 {
  # Resource name of the organization.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing organizations.
struct ListOrganizationsRequest @0xa2afe6050afa0141 {
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @0 :Int32;
  # Page token from a previous call.
  pageToken @1 :Text;
  # Filter expression restricting which organizations are returned.
  filter @2 :Text;
  # Whether to include soft-deleted organizations.
  showDeleted @3 :Bool;
}

# Response message for listing organizations.
struct ListOrganizationsResponse @0xcc225f0e818de1dc {
  # The organizations on this page.
  organizations @0 :List(Organization.Organization);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for updating an organization.
struct UpdateOrganizationRequest @0xa26a9bf246eb7ace {
  # The organization to update, identified by its `name`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  organization @0 :Organization.Organization;
  # Fields to update.
  updateMask @1 :List(Text);
}

# Request message for deleting an organization.
struct DeleteOrganizationRequest @0xc718091c2023ae84 {
  # Resource name of the organization to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
  # Whether to delete the resource even though it still has children.
  #
  # Without this a delete that would orphan children is refused. Deleting
  # is reversible until expiry either way, but refusing by default keeps a
  # mistaken call from tombstoning a whole subtree in one step.
  force @2 :Bool;
}

# Request message for restoring a soft-deleted organization.
struct UndeleteOrganizationRequest @0xe10ccef1a2ea724f {
  # Resource name of the organization to restore.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for creating a project.
struct CreateProjectRequest @0xfac6dc06e5812480 {
  # Organization the project belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  projectId @1 :Text;
  # The project to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  project @2 :Project.Project;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a project.
struct GetProjectRequest @0x938f80d8f258675d {
  # Resource name of the project.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing projects.
struct ListProjectsRequest @0x9a075e78d54c529e {
  # Organization to list projects from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression restricting which projects are returned.
  filter @3 :Text;
  # Whether to include soft-deleted projects.
  showDeleted @4 :Bool;
}

# Response message for listing projects.
struct ListProjectsResponse @0xd814702a57deb8b9 {
  # The projects on this page.
  projects @0 :List(Project.Project);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a project.
struct DeleteProjectRequest @0xbf3e514433c7f463 {
  # Resource name of the project to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for creating a space.
struct CreateSpaceRequest @0xdc941c38fdcce166 {
  # Organization the space belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  spaceId @1 :Text;
  # The space to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  space @2 :Space.Space;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a space.
struct GetSpaceRequest @0xb8ee6734640c9f26 {
  # Resource name of the space.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing spaces.
struct ListSpacesRequest @0xe7ba19f57f50158e {
  # Organization to list spaces from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression restricting which spaces are returned.
  #
  # A space the caller holds no grant on is absent from the result rather
  # than reported as denied: reporting it would disclose that it exists, and
  # for a private thread the existence is often the sensitive part.
  filter @3 :Text;
}

# Response message for listing spaces.
struct ListSpacesResponse @0xc8819d1d78f46734 {
  # The spaces on this page.
  spaces @0 :List(Space.Space);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for unlocking a key-wrapped space.
struct UnlockSpaceRequest @0xd5f8bce9ee1bec7a {
  # Resource name of the space to unlock.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Client-held key material, for a sealed space.
  #
  # Required when protection is SEALED, because the server holds no key that
  # opens it. Never persisted.
  unwrapKey @1 :Data;
}

# Response message for unlocking a space.
struct UnlockSpaceResponse @0xd6822c8bfde12b1a {
  # The space, now reporting `locked` as false.
  space @0 :Space.Space;
  # Segments made readable by this unlock.
  unlockedSegmentCount @1 :Int32;
}

# Request message for deleting a space.
struct DeleteSpaceRequest @0x912cb81c2054347c {
  # Resource name of the space to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for creating a session.
struct CreateSessionRequest @0xaab78009474ac199 {
  # Organization the session belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  sessionId @1 :Text;
  # The session to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  session @2 :Session.Session;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a session.
struct GetSessionRequest @0xdf5749cb32ab2784 {
  # Resource name of the session.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing sessions.
struct ListSessionsRequest @0xf5fafdc133a0b6ea {
  # Organization to list sessions from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression restricting which sessions are returned.
  filter @3 :Text;
}

# Response message for listing sessions.
struct ListSessionsResponse @0xc8bd490516d20d62 {
  # The sessions on this page.
  sessions @0 :List(Session.Session);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a session.
struct DeleteSessionRequest @0xc407e18ae8cb9c98 {
  # Resource name of the session to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}
