@0x9568ebd14b819fc8;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/tenancy/v1/tenancy_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::tenancy::v1");

using Organization = import "/telividb/tenancy/v1/organization.capnp";
using Project = import "/telividb/tenancy/v1/project.capnp";
using Session = import "/telividb/tenancy/v1/session.capnp";
using Space = import "/telividb/tenancy/v1/space.capnp";
using TenancyMessages = import "/telividb/tenancy/v1/tenancy_messages.capnp";

# Manages organizations, the root of the tenancy tree.
#
# Every destructive method here returns the resource it acted on rather than
# an empty message. That is the soft-delete form, and it is not a workaround
# for a house style: deletion tombstones the resource so queries exclude it
# immediately and compaction reclaims the bytes later, so the resource still
# exists and describing it is the truthful response. An empty return would
# also be a dead end — a method returning it can never gain a field without a
# breaking change to a shipped signature.
interface Organizations @0x94308e8ba0e0e59c {
  # Creates an organization and the collection backing it.
  # AIP-133 standard method.
  createOrganization @0 (request :TenancyMessages.CreateOrganizationRequest) -> (response :Organization.Organization);

  # Retrieves a single organization.
  # AIP-131 standard method.
  getOrganization @1 (request :TenancyMessages.GetOrganizationRequest) -> (response :Organization.Organization);

  # Lists organizations visible to the caller.
  # AIP-132 standard method.
  listOrganizations @2 (request :TenancyMessages.ListOrganizationsRequest) -> (response :TenancyMessages.ListOrganizationsResponse);

  # Updates an organization.
  # AIP-134 standard method.
  updateOrganization @3 (request :TenancyMessages.UpdateOrganizationRequest) -> (response :Organization.Organization);

  # Soft-deletes an organization, tombstoning every collection beneath it.
  #
  # Returns the tombstoned organization carrying `delete_time` and
  # `expire_time`. Nothing is physically removed here: the tenant becomes
  # invisible to queries at once, and the bytes are reclaimed at expiry. Until
  # then the operation is reversible.
  # AIP-135 standard method.
  deleteOrganization @4 (request :TenancyMessages.DeleteOrganizationRequest) -> (response :Organization.Organization);

  # Restores a soft-deleted organization before it expires.
  #
  # This is the rollback that a long-running transaction could not provide:
  # the delete committed atomically in metadata and the data was never
  # touched, so restoring it is another metadata write rather than a replay.
  # AIP-164 standard method.
  undeleteOrganization @5 (request :TenancyMessages.UndeleteOrganizationRequest) -> (response :Organization.Organization);
}

# Manages projects, the unit at which access is granted.
interface Projects @0x85ee2334de8e0c78 {
  # Creates a project.
  # AIP-133 standard method.
  createProject @0 (request :TenancyMessages.CreateProjectRequest) -> (response :Project.Project);

  # Retrieves a single project.
  # AIP-131 standard method.
  getProject @1 (request :TenancyMessages.GetProjectRequest) -> (response :Project.Project);

  # Lists the projects of an organization.
  # AIP-132 standard method.
  listProjects @2 (request :TenancyMessages.ListProjectsRequest) -> (response :TenancyMessages.ListProjectsResponse);

  # Soft-deletes a project. Spaces it contained survive and lose the link.
  # AIP-135 standard method.
  deleteProject @3 (request :TenancyMessages.DeleteProjectRequest) -> (response :Project.Project);
}

# Manages spaces and their protection.
interface Spaces @0xdb087f7846ab61c9 {
  # Creates a space with a declared protection state.
  #
  # Protection is fixed at creation because it determines segment routing: an
  # encrypted space writes into its own segments so unlocking decrypts a
  # region rather than a row at a time. Changing it later is a rewrite, not a
  # field update.
  # AIP-133 standard method.
  createSpace @0 (request :TenancyMessages.CreateSpaceRequest) -> (response :Space.Space);

  # Retrieves a single space.
  # AIP-131 standard method.
  getSpace @1 (request :TenancyMessages.GetSpaceRequest) -> (response :Space.Space);

  # Lists the spaces of an organization that the caller can see.
  # AIP-132 standard method.
  listSpaces @2 (request :TenancyMessages.ListSpacesRequest) -> (response :TenancyMessages.ListSpacesResponse);

  # Unlocks a key-wrapped space for the duration of a session.
  unlockSpace @3 (request :TenancyMessages.UnlockSpaceRequest) -> (response :TenancyMessages.UnlockSpaceResponse);

  # Soft-deletes a space and every conversation within it.
  # AIP-135 standard method.
  deleteSpace @4 (request :TenancyMessages.DeleteSpaceRequest) -> (response :Space.Space);
}

# Manages sessions — recorded working periods holding conversations.
interface Sessions @0xad7573bdf079e577 {
  # Creates a session.
  # AIP-133 standard method.
  createSession @0 (request :TenancyMessages.CreateSessionRequest) -> (response :Session.Session);

  # Retrieves a single session.
  # AIP-131 standard method.
  getSession @1 (request :TenancyMessages.GetSessionRequest) -> (response :Session.Session);

  # Lists the sessions of an organization.
  # AIP-132 standard method.
  listSessions @2 (request :TenancyMessages.ListSessionsRequest) -> (response :TenancyMessages.ListSessionsResponse);

  # Soft-deletes a session. Its conversations survive and lose the link.
  # AIP-135 standard method.
  deleteSession @3 (request :TenancyMessages.DeleteSessionRequest) -> (response :Session.Session);
}
