// @generated by `cargo xtask gen-buffers`. DO NOT EDIT.
//! Cap'n Proto and FlatBuffers views of the protobuf schema of record.
//!
//! # Generated, not built
//!
//! Everything here is produced from `buffers/protobuf/` — by `buf` for the
//! protobuf views, by `buffers` for the flat ones — and **committed**. So
//! `cargo build` needs no protobuf toolchain, no `capnp` and no `flatc`: a
//! contributor clones and builds with rustup alone.
//!
//! # One crate, one schema, three renderings
//!
//! Protobuf, Cap'n Proto and FlatBuffers are not three schemas that happen to
//! agree — they are one schema rendered three ways, with `buffers.lock` keeping
//! a field in the same slot across numbering schemes that do not correspond.
//! Splitting them across crates would have invited them to drift.
//!
//! Regenerate with `cargo xtask gen-buffers`; CI runs `check-buffers` and fails
//! if the committed output has drifted from the protos.
//!
//! # One module per format, and why the private layer exists
//!
//! Callers reach these as [`capnp`] and [`flatbuffers`], and a third format
//! would be a third module beside them. That grouping is not what the
//! generators produce, though, and the gap is worth understanding before anyone
//! tries to tidy it away.
//!
//! Both `capnpc-rust` and `flatc` emit code that addresses its siblings
//! absolutely — `crate::message_capnp`, `crate::wellknown_generated` — so every
//! generated module must exist at the crate root or the generated code stops
//! compiling. Nesting them under `capnp::` would mean editing generated files,
//! which is the one thing a generated tree must never require.
//!
//! So the roots stay where the generators expect them, hidden from the docs,
//! and each format re-exports its own through a facade. Files live in
//! `generated/<format>/`, the public API is grouped by format, and not one
//! generated line is touched.
//!
//! The two sets coexist only because the `_capnp` and `_generated` suffixes
//! keep them disjoint. A third format must carry its own suffix for the same
//! reason.
//!
//! # FlatBuffers is opt-in, and the reason is `unsafe`
//!
//! FlatBuffers reads a field by pointing at bytes and trusting the layout, so
//! its generated accessors are `unsafe` by construction. Cap'n Proto validates
//! as it reads and generates none.
//!
//! Every crate here outside a short sanctioned list carries
//! `forbid(unsafe_code)`, and that containment is worth more than the
//! convenience of a default feature — so `unsafe` is forbidden unless the
//! `flatbuffers` feature is on, the same quarantine the optional FAISS index
//! gets rather than admission to the default build.
//!
//! Turn it on when something actually wires the FlatBuffers path: a contiguous
//! single-buffer layout is what a one-sided RDMA write wants, and that is the
//! case worth paying the `unsafe` for.
#![cfg_attr(not(feature = "flatbuffers"), forbid(unsafe_code))]
#![allow(missing_docs, clippy::all, rustdoc::all)]

// Roots the generators require at the crate root. Hidden: the grouped
// modules below are the surface a caller is meant to find.

#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/collection/v1/collection_capnp.rs"]
#[doc(hidden)]
pub mod collection_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/collection/v1/collection_messages_capnp.rs"]
#[doc(hidden)]
pub mod collection_messages_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/collection/v1/collection_service_capnp.rs"]
#[doc(hidden)]
pub mod collection_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/context/v1/context_service_capnp.rs"]
#[doc(hidden)]
pub mod context_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/context/v1/context_template_capnp.rs"]
#[doc(hidden)]
pub mod context_template_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/conversation/v1/conversation_capnp.rs"]
#[doc(hidden)]
pub mod conversation_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/conversation/v1/conversation_messages_capnp.rs"]
#[doc(hidden)]
pub mod conversation_messages_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/conversation/v1/conversation_service_capnp.rs"]
#[doc(hidden)]
pub mod conversation_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/graph/v1/edge_capnp.rs"]
#[doc(hidden)]
pub mod edge_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/graph/v1/graph_messages_capnp.rs"]
#[doc(hidden)]
pub mod graph_messages_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/graph/v1/graph_service_capnp.rs"]
#[doc(hidden)]
pub mod graph_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/identity/v1/identity_service_capnp.rs"]
#[doc(hidden)]
pub mod identity_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/inference/v1/inference_service_capnp.rs"]
#[doc(hidden)]
pub mod inference_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/mcp/v1/mcp_server_capnp.rs"]
#[doc(hidden)]
pub mod mcp_server_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/mcp/v1/mcp_service_capnp.rs"]
#[doc(hidden)]
pub mod mcp_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/conversation/v1/message_capnp.rs"]
#[doc(hidden)]
pub mod message_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/inference/v1/model_capnp.rs"]
#[doc(hidden)]
pub mod model_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/tenancy/v1/organization_capnp.rs"]
#[doc(hidden)]
pub mod organization_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/point/v1/point_capnp.rs"]
#[doc(hidden)]
pub mod point_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/point/v1/point_messages_capnp.rs"]
#[doc(hidden)]
pub mod point_messages_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/point/v1/point_search_capnp.rs"]
#[doc(hidden)]
pub mod point_search_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/point/v1/point_service_capnp.rs"]
#[doc(hidden)]
pub mod point_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/policy/v1/policy_service_capnp.rs"]
#[doc(hidden)]
pub mod policy_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/policy/v1/policy_set_capnp.rs"]
#[doc(hidden)]
pub mod policy_set_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/identity/v1/principal_capnp.rs"]
#[doc(hidden)]
pub mod principal_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/tenancy/v1/project_capnp.rs"]
#[doc(hidden)]
pub mod project_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/tenancy/v1/session_capnp.rs"]
#[doc(hidden)]
pub mod session_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/tenancy/v1/space_capnp.rs"]
#[doc(hidden)]
pub mod space_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/conversation/v1/summary_capnp.rs"]
#[doc(hidden)]
pub mod summary_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/system/v1/system_capnp.rs"]
#[doc(hidden)]
pub mod system_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/system/v1/system_service_capnp.rs"]
#[doc(hidden)]
pub mod system_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/tenancy/v1/tenancy_messages_capnp.rs"]
#[doc(hidden)]
pub mod tenancy_messages_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/tenancy/v1/tenancy_service_capnp.rs"]
#[doc(hidden)]
pub mod tenancy_service_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/conversation/v1/tool_invocation_capnp.rs"]
#[doc(hidden)]
pub mod tool_invocation_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/telividb/graph/v1/traversal_capnp.rs"]
#[doc(hidden)]
pub mod traversal_capnp;
#[cfg(feature = "capnp")]
#[path = "generated/capnp/buffers/wellknown_capnp.rs"]
#[doc(hidden)]
pub mod wellknown_capnp;

#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/collection/v1/collection_generated.rs"]
#[doc(hidden)]
pub mod collection_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/collection/v1/collection_messages_generated.rs"]
#[doc(hidden)]
pub mod collection_messages_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/context/v1/context_service_generated.rs"]
#[doc(hidden)]
pub mod context_service_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/context/v1/context_template_generated.rs"]
#[doc(hidden)]
pub mod context_template_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/conversation/v1/conversation_generated.rs"]
#[doc(hidden)]
pub mod conversation_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/conversation/v1/conversation_messages_generated.rs"]
#[doc(hidden)]
pub mod conversation_messages_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/graph/v1/edge_generated.rs"]
#[doc(hidden)]
pub mod edge_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/graph/v1/graph_messages_generated.rs"]
#[doc(hidden)]
pub mod graph_messages_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/identity/v1/identity_service_generated.rs"]
#[doc(hidden)]
pub mod identity_service_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/inference/v1/inference_service_generated.rs"]
#[doc(hidden)]
pub mod inference_service_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/mcp/v1/mcp_server_generated.rs"]
#[doc(hidden)]
pub mod mcp_server_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/mcp/v1/mcp_service_generated.rs"]
#[doc(hidden)]
pub mod mcp_service_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/conversation/v1/message_generated.rs"]
#[doc(hidden)]
pub mod message_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/inference/v1/model_generated.rs"]
#[doc(hidden)]
pub mod model_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/tenancy/v1/organization_generated.rs"]
#[doc(hidden)]
pub mod organization_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/point/v1/point_generated.rs"]
#[doc(hidden)]
pub mod point_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/point/v1/point_messages_generated.rs"]
#[doc(hidden)]
pub mod point_messages_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/point/v1/point_search_generated.rs"]
#[doc(hidden)]
pub mod point_search_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/policy/v1/policy_service_generated.rs"]
#[doc(hidden)]
pub mod policy_service_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/policy/v1/policy_set_generated.rs"]
#[doc(hidden)]
pub mod policy_set_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/identity/v1/principal_generated.rs"]
#[doc(hidden)]
pub mod principal_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/tenancy/v1/project_generated.rs"]
#[doc(hidden)]
pub mod project_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/tenancy/v1/session_generated.rs"]
#[doc(hidden)]
pub mod session_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/tenancy/v1/space_generated.rs"]
#[doc(hidden)]
pub mod space_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/conversation/v1/summary_generated.rs"]
#[doc(hidden)]
pub mod summary_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/system/v1/system_generated.rs"]
#[doc(hidden)]
pub mod system_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/system/v1/system_service_generated.rs"]
#[doc(hidden)]
pub mod system_service_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/tenancy/v1/tenancy_messages_generated.rs"]
#[doc(hidden)]
pub mod tenancy_messages_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/conversation/v1/tool_invocation_generated.rs"]
#[doc(hidden)]
pub mod tool_invocation_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/telividb/graph/v1/traversal_generated.rs"]
#[doc(hidden)]
pub mod traversal_generated;
#[cfg(feature = "flatbuffers")]
#[path = "generated/flatbuffers/buffers/wellknown_generated.rs"]
#[doc(hidden)]
pub mod wellknown_generated;

/// Protobuf views and the gRPC service stubs, the wire protocol the
/// server speaks. Nested directly: `prost` addresses siblings
/// relatively, so unlike the flat formats these need no root layer.
#[cfg(feature = "protobuf")]
pub mod protobuf {
    /// `collection`.
    pub mod collection {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/collection/v1/telividb.collection.v1.rs");
            include!("generated/protobuf/telividb/collection/v1/telividb.collection.v1.tonic.rs");
        }
    }
    /// `context`.
    pub mod context {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/context/v1/telividb.context.v1.rs");
            include!("generated/protobuf/telividb/context/v1/telividb.context.v1.tonic.rs");
        }
    }
    /// `conversation`.
    pub mod conversation {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/conversation/v1/telividb.conversation.v1.rs");
            include!(
                "generated/protobuf/telividb/conversation/v1/telividb.conversation.v1.tonic.rs"
            );
        }
    }
    /// `graph`.
    pub mod graph {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/graph/v1/telividb.graph.v1.rs");
            include!("generated/protobuf/telividb/graph/v1/telividb.graph.v1.tonic.rs");
        }
    }
    /// `identity`.
    pub mod identity {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/identity/v1/telividb.identity.v1.rs");
            include!("generated/protobuf/telividb/identity/v1/telividb.identity.v1.tonic.rs");
        }
    }
    /// `inference`.
    pub mod inference {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/inference/v1/telividb.inference.v1.rs");
            include!("generated/protobuf/telividb/inference/v1/telividb.inference.v1.tonic.rs");
        }
    }
    /// `mcp`.
    pub mod mcp {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/mcp/v1/telividb.mcp.v1.rs");
            include!("generated/protobuf/telividb/mcp/v1/telividb.mcp.v1.tonic.rs");
        }
    }
    /// `point`.
    pub mod point {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/point/v1/telividb.point.v1.rs");
            include!("generated/protobuf/telividb/point/v1/telividb.point.v1.tonic.rs");
        }
    }
    /// `policy`.
    pub mod policy {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/policy/v1/telividb.policy.v1.rs");
            include!("generated/protobuf/telividb/policy/v1/telividb.policy.v1.tonic.rs");
        }
    }
    /// `system`.
    pub mod system {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/system/v1/telividb.system.v1.rs");
            include!("generated/protobuf/telividb/system/v1/telividb.system.v1.tonic.rs");
        }
    }
    /// `tenancy`.
    pub mod tenancy {
        /// `v1`.
        pub mod v1 {
            include!("generated/protobuf/telividb/tenancy/v1/telividb.tenancy.v1.rs");
            include!("generated/protobuf/telividb/tenancy/v1/telividb.tenancy.v1.tonic.rs");
        }
    }
    /// Serialized `FileDescriptorSet` for every service here.
    ///
    /// Served over gRPC reflection so generic clients can introspect the
    /// API without being shipped the protos first.
    pub const FILE_DESCRIPTOR_SET: &[u8] = include_bytes!("generated/protobuf/descriptor.bin");
}

// The documented surface: one module per format, nested by package.

/// Cap'n Proto views. Validated reads, no `unsafe`, on by default.
#[cfg(feature = "capnp")]
pub mod capnp {
    /// `buffers` schemas.
    pub mod buffers {
        pub use crate::wellknown_capnp;
    }
    /// `collection` schemas.
    pub mod collection {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                collection_capnp, collection_messages_capnp, collection_service_capnp,
            };
        }
    }
    /// `context` schemas.
    pub mod context {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{context_service_capnp, context_template_capnp};
        }
    }
    /// `conversation` schemas.
    pub mod conversation {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                conversation_capnp, conversation_messages_capnp, conversation_service_capnp,
                message_capnp, summary_capnp, tool_invocation_capnp,
            };
        }
    }
    /// `graph` schemas.
    pub mod graph {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                edge_capnp, graph_messages_capnp, graph_service_capnp, traversal_capnp,
            };
        }
    }
    /// `identity` schemas.
    pub mod identity {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{identity_service_capnp, principal_capnp};
        }
    }
    /// `inference` schemas.
    pub mod inference {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{inference_service_capnp, model_capnp};
        }
    }
    /// `mcp` schemas.
    pub mod mcp {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{mcp_server_capnp, mcp_service_capnp};
        }
    }
    /// `point` schemas.
    pub mod point {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                point_capnp, point_messages_capnp, point_search_capnp, point_service_capnp,
            };
        }
    }
    /// `policy` schemas.
    pub mod policy {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{policy_service_capnp, policy_set_capnp};
        }
    }
    /// `system` schemas.
    pub mod system {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{system_capnp, system_service_capnp};
        }
    }
    /// `tenancy` schemas.
    pub mod tenancy {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                organization_capnp, project_capnp, session_capnp, space_capnp,
                tenancy_messages_capnp, tenancy_service_capnp,
            };
        }
    }
}

/// FlatBuffers views. Zero-copy reads, `unsafe` accessors, opt-in.
#[cfg(feature = "flatbuffers")]
pub mod flatbuffers {
    /// `buffers` schemas.
    pub mod buffers {
        pub use crate::wellknown_generated;
    }
    /// `collection` schemas.
    pub mod collection {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{collection_generated, collection_messages_generated};
        }
    }
    /// `context` schemas.
    pub mod context {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{context_service_generated, context_template_generated};
        }
    }
    /// `conversation` schemas.
    pub mod conversation {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                conversation_generated, conversation_messages_generated, message_generated,
                summary_generated, tool_invocation_generated,
            };
        }
    }
    /// `graph` schemas.
    pub mod graph {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{edge_generated, graph_messages_generated, traversal_generated};
        }
    }
    /// `identity` schemas.
    pub mod identity {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{identity_service_generated, principal_generated};
        }
    }
    /// `inference` schemas.
    pub mod inference {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{inference_service_generated, model_generated};
        }
    }
    /// `mcp` schemas.
    pub mod mcp {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{mcp_server_generated, mcp_service_generated};
        }
    }
    /// `point` schemas.
    pub mod point {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{point_generated, point_messages_generated, point_search_generated};
        }
    }
    /// `policy` schemas.
    pub mod policy {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{policy_service_generated, policy_set_generated};
        }
    }
    /// `system` schemas.
    pub mod system {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{system_generated, system_service_generated};
        }
    }
    /// `tenancy` schemas.
    pub mod tenancy {
        /// `v1` schemas.
        pub mod v1 {
            pub use crate::{
                organization_generated, project_generated, session_generated, space_generated,
                tenancy_messages_generated,
            };
        }
    }
}
