@0xf5cf9d523c1e6b18;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/policy/v1/policy_set.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::policy::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Whether a request is permitted.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Effect @0xaec6533ced3ff7ea {
  # Default value. Treated as a denial.
  unspecified @0;
  # The request proceeds, restricted by the accompanying predicate.
  allow @1;
  # The request is refused, and the refusal is reported rather than returned
  # as an empty result.
  deny @2;
}

# A set of rules attached to groups, evaluated before any index runs.
struct PolicySet @0xd1258f8d84d4c454 {
  # Resource name of the policy set.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # The rules, as a policy-language module.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  source @2 :Text;
  # Monotonic version, incremented on every change.
  #
  # Compiled visibility is cached on the principal, the collection and this
  # number together, so a policy change invalidates the cache exactly rather
  # than by timeout.
  version @3 :Int64;
  # Groups this set is attached to.
  userGroups @4 :List(Text);
  # When the policy set was created.
  createTime @5 :Wellknown.Timestamp;
  # When the policy set was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # When the policy set was soft-deleted, or unset while live.
  deleteTime @7 :Wellknown.Timestamp;
  # When a soft-deleted policy set is purged and becomes unrecoverable.
  expireTime @8 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @9 :Text;
}

# What a principal is allowed to see.
#
# A predicate, never a boolean. A boolean cannot express row-level visibility
# and cannot be retrofitted into one cheaply — and the predicate is ANDed into
# the query before the index runs, because searching first and discarding
# afterwards leaks the existence, count and ranking of rows the caller was
# never allowed to know about.
struct Decision @0xb470a26bbf47ce39 {
  # Whether the request is permitted at all.
  #
  # Absent policy denies. Failing open would make a misconfiguration
  # indistinguishable from a grant.
  effect @0 :Effect;
  # Row visibility, as a filter expression to AND into the query.
  rowPredicate @1 :Text;
  # Fields the principal may read.
  fieldMask @2 :List(Text);
  # Policy version this was resolved against.
  policyVersion @3 :Int64;
}
