@0x86df3361d79cc2ba;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/policy/v1/policy_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::policy::v1");

using PolicySet = import "/telividb/policy/v1/policy_set.capnp";

# Request message for creating a policy set.
struct CreatePolicySetRequest @0xa76d6af5787adff5 {
  # Organization the policy set belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  policySetId @1 :Text;
  # The policy set to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  policySet @2 :PolicySet.PolicySet;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a policy set.
struct GetPolicySetRequest @0xe63ccf9cb2893faa {
  # Resource name of the policy set.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing policy sets.
struct ListPolicySetsRequest @0xa4d8e4ea864d5a7a {
  # Organization to list policy sets from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression restricting which policy sets are returned.
  filter @3 :Text;
  # Whether to include soft-deleted policy sets.
  showDeleted @4 :Bool;
}

# Response message for listing policy sets.
struct ListPolicySetsResponse @0xf521bfa643255df7 {
  # The policy sets on this page.
  policySets @0 :List(PolicySet.PolicySet);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a policy set.
struct DeletePolicySetRequest @0xe44f77836be991b1 {
  # Resource name of the policy set to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for evaluating policy without applying it.
struct EvaluatePolicyRequest @0xdfc9bcd1b408fb50 {
  # Organization the evaluation runs in.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The principal to evaluate for.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  principal @1 :Text;
  # The resource the principal is trying to reach.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  resource @2 :Text;
  # The operation being attempted, such as `read` or `read_vector`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  operation @3 :Text;
}

# Response message for evaluating policy.
struct EvaluatePolicyResponse @0xbf43753eac44287a {
  # What the principal would be permitted to see.
  decision @0 :PolicySet.Decision;
}

# Manages policy sets and answers what a principal would be able to see.
#
# One predicate covers every access path. A row reached by graph traversal is
# checked against the same predicate as a row reached by nearest-neighbour
# search — writing a second authorization path for the graph is how two
# systems that must agree drift apart and leak.
interface Policy @0xf70c6988e73bfced {
  # Creates a policy set.
  # AIP-133 standard method.
  createPolicySet @0 (request :CreatePolicySetRequest) -> (response :PolicySet.PolicySet);

  # Retrieves a single policy set.
  # AIP-131 standard method.
  getPolicySet @1 (request :GetPolicySetRequest) -> (response :PolicySet.PolicySet);

  # Lists policy sets.
  # AIP-132 standard method.
  listPolicySets @2 (request :ListPolicySetsRequest) -> (response :ListPolicySetsResponse);

  # Soft-deletes a policy set.
  #
  # Removing a policy set does not widen access: absent policy denies, so a
  # deleted set fails closed rather than opening what it used to restrict.
  # AIP-135 standard method.
  deletePolicySet @3 (request :DeletePolicySetRequest) -> (response :PolicySet.PolicySet);

  # Evaluates policy without applying it, returning the resulting decision.
  #
  # The debugging tool for "why did this return nothing". Without it the
  # difference between an empty collection and an effective denial is
  # invisible, and a predicate that silently matches nothing looks exactly
  # like data that is not there.
  evaluatePolicy @4 (request :EvaluatePolicyRequest) -> (response :EvaluatePolicyResponse);
}
