@0x9f97da97d3fab924;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/inference/v1/inference_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::inference::v1");

using Model = import "/telividb/inference/v1/model.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Whether text is being encoded as a document or as a query.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Task @0xea3e5eb4473b70ba {
  # Default value. Treated as a document.
  unspecified @0;
  # Content being stored.
  document @1;
  # A query being matched against stored content.
  query @2;
}

# A vector, carried as raw bytes rather than a repeated scalar.
#
# Protobuf encodes a repeated scalar element by element, so a 768-dimension
# vector would cost 768 varint operations per message in each direction on the
# hot path. One length-delimited field costs one.
struct Vector @0xe270f374d39ea68a {
  # Raw little-endian IEEE-754 single-precision components.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  data @0 :Data;
  # Number of components, so a reader can validate before casting.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  dimensions @1 :Int32;
}

# Request message for retrieving a model.
struct GetModelRequest @0x9ded60485f4e6b50 {
  # Resource name of the model.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing models.
struct ListModelsRequest @0xebf424b4663c0ddc {
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @0 :Int32;
  # Page token from a previous call.
  pageToken @1 :Text;
  # Filter expression, such as `resident = true`.
  filter @2 :Text;
}

# Response message for listing models.
struct ListModelsResponse @0x9a9ab4f844b05b01 {
  # The models on this page.
  models @0 :List(Model.Model);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for computing embeddings.
struct EmbedTextRequest @0xe1da0ce9b8806d30 {
  # Model to encode with.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  model @0 :Text;
  # Text to encode. One or many; the call is the same either way.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  input @1 :List(Text);
  # Whether this is document-side or query-side encoding.
  #
  # Not cosmetic: the two use different prefixes, and for a jointly trained
  # model a query routes to the other tower entirely. Encoding a query through
  # the document tower returns plausible garbage rather than an error.
  task @2 :Task;
  # Whether to truncate input longer than the model's context.
  #
  # Defaults to true. The alternative is failing a batch of ten thousand
  # because one document was long.
  truncate @3 :Bool;
}

# Response message for computing embeddings.
struct EmbedTextResponse @0xf3ef4f7e796f3097 {
  # The vectors, in the order the inputs were given.
  embeddings @0 :List(Vector);
  # Digest of the model that produced them — the identity, not the label.
  modelDigest @1 :Text;
  # Time spent loading the model.
  #
  # Near zero is the proof a model stayed resident rather than being reloaded,
  # which is the difference between batching working and not.
  loadDuration @2 :Wellknown.Duration;
  # Tokens consumed across the batch.
  promptTokenCount @3 :Int32;
}

# Computes vectors, and deliberately does not write them.
#
# Two writers to one store is how provenance diverges: this returns, and the
# points service stores. It is also the single compute boundary — ingest
# embedding, query encoding and every plugin's compute step arrive here, which
# is what makes a permission check before a model runs possible at all.
interface Inference @0x8b9ed8722e3980f7 {
  # Retrieves a single model.
  # AIP-131 standard method.
  getModel @0 (request :GetModelRequest) -> (response :Model.Model);

  # Lists models known to the inference server.
  # AIP-132 standard method.
  listModels @1 (request :ListModelsRequest) -> (response :ListModelsResponse);

  # Computes embeddings for a batch of text.
  #
  # Policy is evaluated before the model runs, not only before results return.
  # That is stronger than checking at the query planner alone: it stops a
  # caller producing a vector for data it was never granted, rather than
  # hiding the output afterwards.
  embedText @2 (request :EmbedTextRequest) -> (response :EmbedTextResponse);
}
