@0x82a1e91a68bac6d0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/inference/v1/model.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::inference::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A GGUF model the inference server can hold resident.
struct Model @0xce267737bb593e96 {
  # Resource name of the model.
  name @0 :Text;
  # Digest of the model file.
  #
  # The identity, not the label. A vector field binds to this rather than to a
  # name, because two files called the same thing produce different vectors and
  # mixing them into one index degrades recall with nothing reporting it.
  # Computed from the bytes read, never trusted from metadata.
  digest @1 :Text;
  # Architecture, read from the file rather than configured.
  architecture @2 :Text;
  # Components in the vectors this model produces.
  dimensions @3 :Int32;
  # Maximum input length in tokens.
  contextLength @4 :Int32;
  # Quantization the file carries, such as `Q4_K_M`.
  quantization @5 :Text;
  # Whether the model is currently loaded on a device.
  #
  # Several models stay resident at once and nothing swaps per call: reloading
  # between calls would defeat the batching that makes in-process inference
  # worth having.
  resident @6 :Bool;
  # Device memory this model occupies while resident.
  residentBytes @7 :Int64;
  # When the model was registered.
  createTime @8 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @9 :Text;
}
