@0xb0ab8dc6163c6b3c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/conversation/v1/conversation_messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::conversation::v1");

using Conversation = import "/telividb/conversation/v1/conversation.capnp";
using Message = import "/telividb/conversation/v1/message.capnp";
using Summary = import "/telividb/conversation/v1/summary.capnp";
using ToolInvocation = import "/telividb/conversation/v1/tool_invocation.capnp";

# Request message for creating a conversation.
struct CreateConversationRequest @0xda758369a0ed2a60 {
  # Organization the conversation belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  conversationId @1 :Text;
  # The conversation to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  conversation @2 :Conversation.Conversation;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a conversation.
struct GetConversationRequest @0x9778e84b1bed7418 {
  # Resource name of the conversation.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing conversations.
struct ListConversationsRequest @0x9a41afe4321b8cdc {
  # Organization to list conversations from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression, such as `space = "organizations/o/spaces/finance"`.
  #
  # Membership is a filter rather than a path segment, which is what lets a
  # conversation move without being renamed.
  #
  # Suppressed conversations are excluded unless the filter asks for them with
  # `suppressed = true`. A suppressed conversation is retained and reachable to
  # its owner deliberately; it is simply not what an unqualified list means.
  filter @3 :Text;
  # How to order the results.
  orderBy @4 :Text;
}

# Response message for listing conversations.
struct ListConversationsResponse @0x8da4050b9651087e {
  # The conversations on this page.
  conversations @0 :List(Conversation.Conversation);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for moving a conversation between containers.
struct MoveConversationRequest @0xac206aa62c929787 {
  # Resource name of the conversation to move.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Session to move it into.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  destinationSession @1 :Text;
}

# Response message for moving a conversation.
struct MoveConversationResponse @0x832628a19b5418e5 {
  # The conversation in its new position. Its name is unchanged.
  conversation @0 :Conversation.Conversation;
  # Summaries invalidated by the move, on both sides.
  #
  # Reported rather than silently corrected: a move changes what each space
  # contains, so summaries covering either side no longer describe it.
  # Regeneration is a job, so the caller learns what is now stale instead of
  # waiting for it.
  invalidatedSummaries @1 :List(Text);
}

# Request message for suppressing a conversation.
struct SuppressConversationRequest @0xedf1f1c7ab55ac47 {
  # Resource name of the conversation to suppress.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for returning a suppressed conversation to ordinary recall.
struct UnsuppressConversationRequest @0x85b7963ab077e2ca {
  # Resource name of the conversation to unsuppress.
  #
  # Only the owner may call this. A classifier may propose suppression and may
  # never lift it — automatic movement is permitted only in the fail-secure
  # direction.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for deleting a conversation.
struct DeleteConversationRequest @0xf7d0cb495c26c5ca {
  # Resource name of the conversation to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
  # Whether to delete the conversation even though it still holds messages.
  force @2 :Bool;
}

# Request message for appending a message to a conversation.
struct CreateMessageRequest @0xc0b8acb62c8f0680 {
  # Conversation to append to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The message to append.
  #
  # Its `parent` field selects where in the graph it attaches. Leaving it
  # unset appends to the conversation's current head; setting it to an earlier
  # message branches from there, which is what regenerating a reply does.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  message @1 :Message.Message;
  # Unique identifier making this request safe to retry.
  requestId @2 :Text;
  # Identifier to use, forming the final path segment.
  messageId @3 :Text;
}

# Request message for listing the messages of a conversation.
struct ListMessagesRequest @0x8078e41bc11b002b {
  # Conversation to list messages from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression over the messages of this conversation.
  #
  # Messages form a directed acyclic graph, so the collection is every branch.
  # `branch = "active"` restricts the result to the path ending at the
  # conversation's head, which is what a transcript means; the default returns
  # all of them, because a discarded attempt is retained deliberately as
  # evidence of what was tried.
  filter @3 :Text;
  # How to order the results.
  orderBy @4 :Text;
}

# Response message for listing messages.
struct ListMessagesResponse @0x98f56717a7752e51 {
  # The messages on this page, oldest first along the requested path.
  messages @0 :List(Message.Message);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for retrieving a message.
struct GetMessageRequest @0xbaf8f34003254e49 {
  # Resource name of the message.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for retrieving a tool invocation.
struct GetToolInvocationRequest @0xca0076ba3b10b87a {
  # Resource name of the invocation.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing the tool invocations of a conversation.
#
# A sibling collection rather than a field on the message list: a call and its
# result are one resource here, and folding them back into the message stream
# would reproduce the two-message split this model exists to avoid.
struct ListToolInvocationsRequest @0x9574668c824bdc87 {
  # Conversation to list invocations from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression, such as `mcp_server = "mcpServers/finance"`.
  filter @3 :Text;
  # How to order the results.
  orderBy @4 :Text;
}

# Response message for listing tool invocations.
struct ListToolInvocationsResponse @0xf89b893a60afa28c {
  # The invocations on this page.
  toolInvocations @0 :List(ToolInvocation.ToolInvocation);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for retrieving a summary.
struct GetSummaryRequest @0x8c6e310f305b5e21 {
  # Resource name of the summary.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing summaries.
struct ListSummariesRequest @0xc97552778fcf49eb {
  # Organization to list summaries from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression selecting which summaries to return.
  #
  # Both the subject and the level are filter terms — `subject =
  # "organizations/o/spaces/finance"` for one space's rolling series, and
  # `level = LEVEL_SPACE` to take only that layer. The level is a declared
  # field rather than something inferred from ordering, so filtering on it is
  # exact.
  filter @3 :Text;
  # How to order the results. Defaults to newest first within a level.
  orderBy @4 :Text;
}

# Response message for listing summaries.
struct ListSummariesResponse @0xbf9848f9f22db2ee {
  # The summaries on this page, newest first within their level.
  summaries @0 :List(Summary.Summary);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}
