@0xfddfb6e571ef529e;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/conversation/v1/conversation_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::conversation::v1");

using Conversation = import "/telividb/conversation/v1/conversation.capnp";
using ConversationMessages = import "/telividb/conversation/v1/conversation_messages.capnp";
using Message = import "/telividb/conversation/v1/message.capnp";
using Summary = import "/telividb/conversation/v1/summary.capnp";
using ToolInvocation = import "/telividb/conversation/v1/tool_invocation.capnp";

# Manages conversations and the messages within them.
interface Conversations @0xe8d434c94f5293f4 {
  # Creates a conversation.
  # AIP-133 standard method.
  createConversation @0 (request :ConversationMessages.CreateConversationRequest) -> (response :Conversation.Conversation);

  # Retrieves a single conversation.
  # AIP-131 standard method.
  getConversation @1 (request :ConversationMessages.GetConversationRequest) -> (response :Conversation.Conversation);

  # Lists conversations, filtered by space, session or project.
  # AIP-132 standard method.
  listConversations @2 (request :ConversationMessages.ListConversationsRequest) -> (response :ConversationMessages.ListConversationsResponse);

  # Moves a conversation into another session, and so into another space.
  #
  # The resource name does not change, which is the entire reason session and
  # space are fields rather than path segments: a move that renamed the
  # conversation would invalidate every edge endpoint, archive entry and
  # citation that refers to it.
  #
  # The move itself is a metadata transaction. No vector data is touched,
  # because membership is never written into a segment — which is what makes
  # this cheap rather than a rewrite.
  moveConversation @3 (request :ConversationMessages.MoveConversationRequest) -> (response :ConversationMessages.MoveConversationResponse);

  # Excludes a conversation from ordinary recall without deleting it.
  #
  # Suppression is a third state, distinct from deletion and from a policy
  # denial: the content is retained, its owner can still reach it deliberately,
  # and traversal stops at it rather than ranking it low. Its existence stays
  # visible to a caller assembling context — so an agent knows what not to
  # raise — while the rendered answer must not surface it, because delivering
  # the reminder is the harm suppression was asked for.
  #
  # A separate method rather than a field update so that setting it is its own
  # audit entry. Only the owner may call it; a classifier may propose
  # suppression and may never apply or lift it.
  suppressConversation @4 (request :ConversationMessages.SuppressConversationRequest) -> (response :Conversation.Conversation);

  # Returns a suppressed conversation to ordinary recall.
  unsuppressConversation @5 (request :ConversationMessages.UnsuppressConversationRequest) -> (response :Conversation.Conversation);

  # Soft-deletes a conversation and the messages beneath it.
  # AIP-135 standard method.
  deleteConversation @6 (request :ConversationMessages.DeleteConversationRequest) -> (response :Conversation.Conversation);

  # Appends a message, branching where the request says to.
  #
  # Embedding happens server-side through the one inference server, so the
  # model that produced a field's vectors is a property of the server rather
  # than of whichever client wrote them. System and developer turns are stored
  # without being encoded.
  # AIP-133 standard method.
  createMessage @7 (request :ConversationMessages.CreateMessageRequest) -> (response :Message.Message);

  # Retrieves a single message.
  # AIP-131 standard method.
  getMessage @8 (request :ConversationMessages.GetMessageRequest) -> (response :Message.Message);

  # Lists the messages of a conversation, every branch by default.
  # AIP-132 standard method.
  listMessages @9 (request :ConversationMessages.ListMessagesRequest) -> (response :ConversationMessages.ListMessagesResponse);

  # Retrieves a single tool invocation.
  # AIP-131 standard method.
  getToolInvocation @10 (request :ConversationMessages.GetToolInvocationRequest) -> (response :ToolInvocation.ToolInvocation);

  # Lists the tool invocations of a conversation.
  #
  # A collection of its own rather than a field on the message list. A call and
  # its result are one resource here, and returning them inside the message
  # stream would rebuild the two-message split this model exists to avoid.
  # AIP-132 standard method.
  listToolInvocations @11 (request :ConversationMessages.ListToolInvocationsRequest) -> (response :ConversationMessages.ListToolInvocationsResponse);

  # Retrieves a single summary.
  # AIP-131 standard method.
  getSummary @12 (request :ConversationMessages.GetSummaryRequest) -> (response :Summary.Summary);

  # Lists summaries, filtered by subject and level.
  #
  # The coarse tier of retrieval: a search runs against these first and
  # expands into messages only where it needs to. Each carries the watermark
  # it reached and whether its subject has changed since, so a stale summary
  # is served honestly rather than passed off as current.
  # AIP-132 standard method.
  listSummaries @13 (request :ConversationMessages.ListSummariesRequest) -> (response :ConversationMessages.ListSummariesResponse);
}
