@0xf37242bc75149a99;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/conversation/v1/conversation.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::conversation::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# An exchange of messages, and the unit that moves between spaces.
#
# Named under its organization and nothing else. Session, space and project
# are fields rather than path segments because a conversation moves between
# them, and a move that renamed the resource would break every stored edge
# endpoint, every archived reference and every citation in an assembled
# answer — external names are the only portable identity there is.
struct Conversation @0xea4a631361376198 {
  # Resource name of the conversation.
  name @0 :Text;
  # Human-readable name.
  displayName @1 :Text;
  # Session this conversation was recorded in.
  session @2 :Text;
  # The message currently at the end of the active branch.
  #
  # Messages form a directed acyclic graph rather than a chain: regenerating a
  # reply or editing and resubmitting creates a sibling, so a message may have
  # several children. This names which leaf the default retrieval path ends
  # at; other branches remain reachable but are not followed by default.
  head @3 :Text;
  # Whether this conversation is excluded from ordinary recall.
  #
  # Suppression retains the content and leaves it reachable to its owner
  # deliberately, while stopping traversal and keeping it out of assembled
  # context. It is a recall preference over the owner's own memory, never an
  # access-control mechanism — a principal denied by policy is denied whether
  # this is set or not.
  suppressed @4 :Bool;
  # Messages on the active branch.
  messageCount @5 :Int32;
  # When the conversation was created.
  createTime @6 :Wellknown.Timestamp;
  # When the conversation was last modified.
  updateTime @7 :Wellknown.Timestamp;
  # When the conversation was soft-deleted, or unset while it is live.
  deleteTime @8 :Wellknown.Timestamp;
  # When a soft-deleted conversation is purged and becomes unrecoverable.
  expireTime @9 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @10 :Text;
}
