@0xde0313ab5271f3d2;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/conversation/v1/message.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::conversation::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Who produced a turn.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Role @0x82be4e1104f3a70b {
  # Default value. Never valid in a request.
  unspecified @0;
  # A human participant.
  user @1;
  # A model response.
  assistant @2;
  # Instructions framing the exchange.
  system @3;
  # Operator instructions ranking above system content.
  developer @4;
  # The result of a tool invocation, projected back as a message on the way
  # out. Stored as an invocation rather than as a turn.
  tool @5;
}

# A pointer to the bytes a message was derived from.
#
# Declared here rather than imported: a package that reached into a shared one
# would couple its versioning to that package's, which AIP-215 forbids.
struct ContentRef @0x975ccd178064526e {
  # Location of the source, such as `file://`, `s3://` or `https://`.
  uri @0 :Text;
  # SHA-256 digest of the referenced bytes.
  #
  # What detects that a source changed and anything derived from it — an
  # embedding, a summary — is now stale.
  sha256 @1 :Data;
  # Source text, inlined when small enough to keep the message re-embeddable.
  #
  # Without a reachable source, content is locked to the model that first
  # encoded it.
  inlineText @2 :Text;
}

# One turn in a conversation.
#
# Modelled on the OpenAI chat message because that vocabulary is universal and
# round-trips into every agent framework — but *projected* to that shape at
# the boundary rather than stored in it. That format is not a specification
# and it churns, and a stored field number is permanent.
#
# A message is one resource and several stored points: long content is chunked
# for the encoder, and each chunk records which part of this message it covers.
struct Message @0x95bc1bec8cfd2341 {
  # Resource name of the message.
  name @0 :Text;
  # Who produced this turn.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  role @1 :Role;
  # The message this one replies to.
  #
  # A message may have several children: regenerating or editing branches the
  # conversation rather than replacing what was there. Discarded branches are
  # retained, because an abandoned attempt is evidence about what was tried.
  parent @2 :Text;
  # Textual content of the turn.
  content @3 :Text;
  # Reference to the bytes this message was derived from, for content too
  # large to inline.
  contentRef @4 :ContentRef;
  # Whether this message contributed vectors to the index.
  #
  # Not every turn is embedded. System and developer content is boilerplate
  # that ranks against real content and degrades retrieval, so it is stored
  # and searchable by filter without being encoded.
  embedded @5 :Bool;
  # When the turn occurred.
  #
  # Time is a ranking term here rather than only a filter: "what did we
  # discuss last Tuesday" has a weak semantic signal and a strong temporal one.
  occurTime @6 :Wellknown.Timestamp;
  # When the message was recorded.
  createTime @7 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @8 :Text;
}
