@0xef8fb6ae0d259bd1;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/conversation/v1/summary.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::conversation::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Which layer of the tenancy tree a summary condenses.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Level @0xc78426ab64830f95 {
  # Default value. Never valid in a request.
  unspecified @0;
  # Messages along one branch of a conversation.
  conversation @1;
  # The conversations recorded in one session.
  session @2;
  # The sessions in one space — the rolling series.
  space @3;
  # The spaces in one project.
  project @4;
}

# A condensation of what a region of memory contains.
#
# Summaries form the coarse tier of a two-tier retrieval: a search runs
# against them first, then expands along the edges recording what each one
# covers. That is the same coarse-to-fine shape the vector path already uses
# when a quantized scan narrows the field before a full-precision rerank,
# applied at the semantic layer instead of the numeric one.
struct Summary @0xae64bdabf436c407 {
  # Resource name of the summary.
  name @0 :Text;
  # Which layer of the tree this summarizes.
  #
  # Declared rather than inferred from ordering. "Newest first" sorts within a
  # level; it does not distinguish a conversation summary from a space one,
  # and a series that relies on recency to tell them apart cannot answer
  # "summarize this space" without re-deriving which entries were which.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  level @1 :Level;
  # The resource this summary is attached to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  subject @2 :Text;
  # The summary text.
  content @3 :Text;
  # How far into the subject this summary reached — its watermark.
  #
  # A summary is derived data and goes stale: a new message extends past it, a
  # branch changes which messages are on the active path, and a conversation
  # moving between spaces invalidates summaries on both sides. The watermark
  # This is what makes staleness detectable rather than silent.
  coverageEndTime @4 :Wellknown.Timestamp;
  # Whether the subject has changed since this summary was generated.
  #
  # A stale summary is still served, marked, with its watermark — an old
  # summary plus an honest marker is more useful than a gap, and serving one
  # as current is the failure with no symptom.
  stale @5 :Bool;
  # Digest of the model that produced this summary.
  #
  # The identity, not a label. A summary that turns out to be wrong is traced
  # to the run that produced it and re-derived.
  modelDigest @6 :Text;
  # Strictest protection among the sources this summary covers.
  #
  # A summary of protected content is protected content: it is derived from
  # the text and leaks it regardless of what guards the original. A summary
  # spanning several spaces takes the most restrictive protection of any of
  # them, never the average and never the destination's — otherwise
  # summarizing across a boundary would be a declassification channel.
  inheritedProtection @7 :Text;
  # When the summary was generated.
  createTime @8 :Wellknown.Timestamp;
}
