@0xafe3c091aa2f8afd;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/conversation/v1/tool_invocation.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::conversation::v1");

using Message = import "/telividb/conversation/v1/message.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Lifecycle state of a tool call.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum State @0xdaf397a254e89f40 {
  # Default value. Never valid in a response.
  unspecified @0;
  # The tool returned a result.
  succeeded @1;
  # The tool reported a failure. The result carries its message.
  failed @2;
  # The call did not complete within its deadline.
  timedOut @3;
}

# One tool call and the result it returned.
#
# A call and its result are one event with one lifetime and one set of
# permissions. The OpenAI wire format splits them across two messages — the
# call embedded in an assistant turn, the result as a separate turn keyed by
# `tool_call_id` — but that split is an artefact of JSON having no way to
# express a cross-message reference. Here the reference is an edge, and the
# two-message form is reconstructed deterministically on the way out.
struct ToolInvocation @0x8dc15365a209ee0f {
  # Resource name of the invocation.
  name @0 :Text;
  # The message that triggered this call.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  caller @1 :Text;
  # Identifier carried by the originating format, preserved for round-trip.
  #
  # Stored so a conversation exported back to an OpenAI-shaped transcript
  # reproduces the same `tool_call_id` it arrived with. Never used internally
  # to resolve the relationship — an edge does that.
  callId @2 :Text;
  # The tool that was called.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  tool @3 :Text;
  # Arguments the tool was called with, JSON-encoded.
  #
  # A string rather than a `Struct`, and that is a deliberate narrowing. The
  # shape is whatever the tool's own JSON Schema declares, so it is not knowable
  # here — and a dynamically typed value has no equivalent in a flat format:
  # rendering it degrades to a JSON string in FlatBuffers and to an opaque
  # pointer in Cap'n Proto that no generated accessor can read. Storing what it
  # actually is keeps every projection of this schema honest.
  #
  # Never embedded. JSON ranks against real content; the useful operations are
  # filtering on `tool` and `mcp_server`, not searching arguments by similarity.
  input @4 :Text;
  # What the tool returned.
  #
  # Inlined when small; a reference when large, because a result can be
  # megabytes and blobs stay outside the database.
  result @5 :Message.ContentRef;
  # Whether the call succeeded.
  state @6 :State;
  # The MCP server that produced this result.
  #
  # Recorded on every invocation whether or not the result was embedded,
  # because provenance is what lets retrieval distinguish something a person
  # said from something a third-party server said. Without it those rank
  # equally as memory, and text returned by a server is written by whoever
  # runs that server.
  mcpServer @7 :Text;
  # Whether the result contributed vectors to the index.
  #
  # False unless the originating server is explicitly marked embeddable. A
  # result that is embedded becomes retrievable memory and can later be
  # assembled into a context window, so an untrusted one is a persistent
  # injection surface rather than a one-time one. The default withholds.
  embedded @8 :Bool;
  # When the call was made.
  createTime @9 :Wellknown.Timestamp;
}
