@0xbd24276406d1989a;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/identity/v1/identity_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::identity::v1");

using Principal = import "/telividb/identity/v1/principal.capnp";

# Request message for creating a user.
struct CreateUserRequest @0x85e69fa02be92f28 {
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  userId @0 :Text;
  # The user to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  user @1 :Principal.User;
  # Unique identifier making this request safe to retry.
  requestId @2 :Text;
}

# Request message for retrieving a user.
struct GetUserRequest @0xc21aa77042911dd2 {
  # Resource name of the user.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing users.
struct ListUsersRequest @0xfb115a32741bbfbc {
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @0 :Int32;
  # Page token from a previous call.
  pageToken @1 :Text;
  # Filter expression restricting which users are returned.
  filter @2 :Text;
  # Whether to include soft-deleted users.
  showDeleted @3 :Bool;
}

# Response message for listing users.
struct ListUsersResponse @0xdbbb8491cd1c7870 {
  # The users on this page.
  users @0 :List(Principal.User);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a user.
struct DeleteUserRequest @0xa95b967584dde300 {
  # Resource name of the user to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
  # Whether to delete the user even though they still own memory.
  force @2 :Bool;
}

# Request message for restoring a soft-deleted user.
struct UndeleteUserRequest @0xb5fca3e99221cada {
  # Resource name of the user to restore.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for creating a user group.
struct CreateUserGroupRequest @0x918649f88e9d5868 {
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  userGroupId @0 :Text;
  # The group to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  userGroup @1 :Principal.UserGroup;
  # Unique identifier making this request safe to retry.
  requestId @2 :Text;
}

# Request message for retrieving a user group.
struct GetUserGroupRequest @0xcd60efca5caf6cd3 {
  # Resource name of the group.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing user groups.
struct ListUserGroupsRequest @0xe0c464f7937a9e18 {
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @0 :Int32;
  # Page token from a previous call.
  pageToken @1 :Text;
  # Filter expression restricting which groups are returned.
  filter @2 :Text;
}

# Response message for listing user groups.
struct ListUserGroupsResponse @0x86fa58844f5c814a {
  # The groups on this page.
  userGroups @0 :List(Principal.UserGroup);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a user group.
struct DeleteUserGroupRequest @0xbf22cd92a67f2611 {
  # Resource name of the group to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for creating a role binding.
struct CreateRoleBindingRequest @0xb8084ba5170c7e52 {
  # Organization the binding belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  roleBindingId @1 :Text;
  # The binding to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  roleBinding @2 :Principal.RoleBinding;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a role binding.
struct GetRoleBindingRequest @0xe26283d3796bac28 {
  # Resource name of the binding.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing role bindings.
struct ListRoleBindingsRequest @0xf271cce51a321444 {
  # Organization to list bindings from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression, such as `scope = "organizations/o/spaces/finance"`.
  filter @3 :Text;
}

# Response message for listing role bindings.
struct ListRoleBindingsResponse @0xc5effb1fd206a473 {
  # The bindings on this page.
  roleBindings @0 :List(Principal.RoleBinding);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a role binding.
struct DeleteRoleBindingRequest @0xa54750bdd7b5d140 {
  # Resource name of the binding to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Manages users, groups and the role bindings that grant over the tree.
interface Identity @0x92bccec50dad3ab2 {
  # Creates a user.
  # AIP-133 standard method.
  createUser @0 (request :CreateUserRequest) -> (response :Principal.User);

  # Retrieves a single user.
  # AIP-131 standard method.
  getUser @1 (request :GetUserRequest) -> (response :Principal.User);

  # Lists users.
  # AIP-132 standard method.
  listUsers @2 (request :ListUsersRequest) -> (response :ListUsersResponse);

  # Soft-deletes a user, cascading to the memory they own.
  # AIP-135 standard method.
  deleteUser @3 (request :DeleteUserRequest) -> (response :Principal.User);

  # Restores a soft-deleted user before they expire.
  # AIP-164 standard method.
  undeleteUser @4 (request :UndeleteUserRequest) -> (response :Principal.User);

  # Creates a user group.
  # AIP-133 standard method.
  createUserGroup @5 (request :CreateUserGroupRequest) -> (response :Principal.UserGroup);

  # Retrieves a single group.
  # AIP-131 standard method.
  getUserGroup @6 (request :GetUserGroupRequest) -> (response :Principal.UserGroup);

  # Lists user groups.
  # AIP-132 standard method.
  listUserGroups @7 (request :ListUserGroupsRequest) -> (response :ListUserGroupsResponse);

  # Soft-deletes a user group.
  # AIP-135 standard method.
  deleteUserGroup @8 (request :DeleteUserGroupRequest) -> (response :Principal.UserGroup);

  # Grants a role to a group over part of the tree.
  # AIP-133 standard method.
  createRoleBinding @9 (request :CreateRoleBindingRequest) -> (response :Principal.RoleBinding);

  # Retrieves a single role binding.
  # AIP-131 standard method.
  getRoleBinding @10 (request :GetRoleBindingRequest) -> (response :Principal.RoleBinding);

  # Lists role bindings.
  # AIP-132 standard method.
  listRoleBindings @11 (request :ListRoleBindingsRequest) -> (response :ListRoleBindingsResponse);

  # Revokes a role binding.
  # AIP-135 standard method.
  deleteRoleBinding @12 (request :DeleteRoleBindingRequest) -> (response :Principal.RoleBinding);
}
