@0x86b1e6d7f78da540;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/identity/v1/principal.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::identity::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A person, and separately the principal policy evaluates against.
#
# A user is two things at once and they are kept apart deliberately: an owner
# of memory, and a principal whose visibility predicate runs on every query.
# Collapsing them would make every permission change a user edit, and grants
# attach to groups rather than to people for the same reason.
struct User @0xb4bb16e45415df9f {
  # Resource name of the user.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # The principal identifier policy evaluates against.
  #
  # Distinct from the resource name so an account can be renamed without
  # rewriting every grant that refers to it.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  principal @2 :Text;
  # Groups this user belongs to.
  userGroups @3 :List(Text);
  # When the user was created.
  createTime @4 :Wellknown.Timestamp;
  # When the user was last modified.
  updateTime @5 :Wellknown.Timestamp;
  # When the user was soft-deleted, or unset while live.
  #
  # Deleting a user cascades to the memory they own. A user delete that left
  # their memory searchable would be the worst bug available here, so the
  # cascade is part of the operation rather than a follow-up.
  deleteTime @6 :Wellknown.Timestamp;
  # When a soft-deleted user is purged and becomes unrecoverable.
  expireTime @7 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @8 :Text;
}

# A set of users that grants attach to.
struct UserGroup @0xfcaa39a08bb1770a {
  # Resource name of the group.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # When the group was created.
  createTime @2 :Wellknown.Timestamp;
  # When the group was last modified.
  updateTime @3 :Wellknown.Timestamp;
  # When the group was soft-deleted, or unset while live.
  deleteTime @4 :Wellknown.Timestamp;
  # When a soft-deleted group is purged and becomes unrecoverable.
  expireTime @5 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @6 :Text;
}

# A role granted to a group over part of the tenancy tree.
#
# Grants attach at an organization, project or space and inherit downward,
# which is what makes "the projects a principal can see" a set small enough to
# compile into a bitmap once per query.
struct RoleBinding @0xd118f565ffa6328e {
  # Resource name of the binding.
  name @0 :Text;
  # The group this grants to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  userGroup @1 :Text;
  # The role granted, such as `reader`, `writer` or `owner`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  role @2 :Text;
  # The resource this applies to — an organization, project or space.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  scope @3 :Text;
  # When the binding was created.
  createTime @4 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @5 :Text;
}
