@0x9f4589eabd864aea;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/graph/v1/edge.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::graph::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A typed relationship between two resources.
#
# Edges relate resources by name, never by internal ordinal: an ordinal is
# segment-local and means nothing outside the process that produced it, so an
# edge carrying one could not survive an export or a compaction.
#
# This one type carries both kinds of relationship in the model — the semantic
# ones a retrieval follows, and the containment ones that place a conversation
# in a session or a session in a space. Keeping them in one graph is what lets
# a visibility predicate and a traversal be answered by the same structure
# rather than by two that must agree.
struct Edge @0xcc8c7842f66a8c5e {
  # Resource name of the edge.
  name @0 :Text;
  # Resource this edge points from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  source @1 :Text;
  # Resource this edge points to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  target @2 :Text;
  # The type of relationship, such as `FOLLOWS` or `IN_SPACE`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  edgeType @3 :Text;
  # Declared strength of this particular relationship.
  #
  # A prior about what this link is worth, overriding the default its type
  # supplies. Weights multiply along a path rather than adding, so two hops
  # through weak edges rank below one hop through a strong one — addition would
  # let a long chain of weak links accumulate into a false strong signal.
  weight @4 :Float32;
  # How live this path is, as a time-decayed count of traversals.
  #
  # Learned evidence, kept separate from `weight` so reinforcement never
  # overwrites the declared prior. Decayed rather than raw because a hundred
  # traversals a year ago and three yesterday are not the same signal, and a
  # separate recency factor over a raw count would double-count age.
  #
  # Accumulated in the resident graph and flushed periodically. The flush is
  # allowed to lose recent increments: this ranks results, it does not audit
  # them, and making every read a durable write would serialize the read path.
  strength @5 :Float32;
  # When this edge was last traversed.
  lastTraverseTime @6 :Wellknown.Timestamp;
  # Whether traversal stops here.
  #
  # A suppressed edge is a hard stop rather than a low score. The content it
  # leads to is retained and its owner can still reach it deliberately; it is
  # excluded from recall, and its existence remains visible to a caller
  # assembling context so an agent knows what not to raise.
  suppressed @7 :Bool;
  # When the edge was created.
  createTime @8 :Wellknown.Timestamp;
  # When the edge was soft-deleted, or unset while it is live.
  deleteTime @9 :Wellknown.Timestamp;
  # When a soft-deleted edge is purged and becomes unrecoverable.
  expireTime @10 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @11 :Text;
}

# A declared kind of relationship, carrying the default weight its edges take.
#
# Declaring the default once means an edge of a given kind inherits a priority
# instead of every edge carrying its own magic number.
struct EdgeType @0xb2c026fd7daa23b7 {
  # Resource name of the edge type.
  name @0 :Text;
  # Human-readable name.
  displayName @1 :Text;
  # Weight edges of this type take unless they override it.
  defaultWeight @2 :Float32;
  # Whether edges of this type express containment rather than meaning.
  #
  # Containment edges place a conversation in a session or a session in a
  # space. They are followed when resolving what a principal can see and are
  # not followed when expanding a retrieval, because membership is not a
  # semantic relationship and would otherwise pull in every sibling.
  structural @3 :Bool;
  # When the edge type was created.
  createTime @4 :Wellknown.Timestamp;
  # When the edge type was soft-deleted, or unset while it is live.
  deleteTime @5 :Wellknown.Timestamp;
  # When a soft-deleted edge type is purged and becomes unrecoverable.
  expireTime @6 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @7 :Text;
}
