@0xfa4241fbee15a1cc;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/graph/v1/graph_messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::graph::v1");

using Edge = import "/telividb/graph/v1/edge.capnp";

# Request message for creating an edge.
struct CreateEdgeRequest @0x856d4713dceb016b {
  # Organization the edge belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  edgeId @1 :Text;
  # The edge to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  edge @2 :Edge.Edge;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving an edge.
struct GetEdgeRequest @0xc33d58a3b6791b58 {
  # Resource name of the edge.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing edges.
struct ListEdgesRequest @0xbc05f8bbccc48abf {
  # Organization to list edges from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression, such as `source = "..." AND edge_type = "..."`.
  filter @3 :Text;
  # How to order the results.
  orderBy @4 :Text;
  # Whether to include soft-deleted edges.
  showDeleted @5 :Bool;
}

# Response message for listing edges.
struct ListEdgesResponse @0xde57e3006dbdbabe {
  # The edges on this page.
  edges @0 :List(Edge.Edge);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for creating several edges at once.
#
# Edges import in a second pass, after the resources they join exist. A batch
# is how that pass is expressed, and one dangling edge follows the configured
# policy rather than silently disappearing.
struct BatchCreateEdgesRequest @0xe504bf2e3b806e0d {
  # Organization the edges belong to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The individual create requests.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  requests @1 :List(CreateEdgeRequest);
}

# Response message for creating several edges at once.
struct BatchCreateEdgesResponse @0xb09e0547c3385767 {
  # The edges that were created.
  edges @0 :List(Edge.Edge);
}

# Request message for deleting an edge.
struct DeleteEdgeRequest @0xa3e4eb2157ad9938 {
  # Resource name of the edge to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for creating an edge type.
struct CreateEdgeTypeRequest @0x9e450ae45bd772dd {
  # Organization the edge type belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  edgeTypeId @1 :Text;
  # The edge type to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  edgeType @2 :Edge.EdgeType;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving an edge type.
struct GetEdgeTypeRequest @0x846ed8d82a9f5385 {
  # Resource name of the edge type.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing edge types.
struct ListEdgeTypesRequest @0x8cdba0684c65e80c {
  # Organization to list edge types from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression restricting which edge types are returned.
  filter @3 :Text;
}

# Response message for listing edge types.
struct ListEdgeTypesResponse @0x8802157c3a736a84 {
  # The edge types on this page.
  edgeTypes @0 :List(Edge.EdgeType);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting an edge type.
struct DeleteEdgeTypeRequest @0xddba430796df6dcb {
  # Resource name of the edge type to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
  # Whether to delete the type even though edges still reference it.
  force @2 :Bool;
}
