@0x835d72e0e5296204;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/graph/v1/graph_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::graph::v1");

using Edge = import "/telividb/graph/v1/edge.capnp";
using GraphMessages = import "/telividb/graph/v1/graph_messages.capnp";
using Traversal = import "/telividb/graph/v1/traversal.capnp";

# Manages edges and traverses the graph they form.
#
# The engine beneath this — edge storage, rehydration into an in-memory graph,
# and hop-bounded traversal with type filtering — is built and tested. Nothing
# could reach it until this service existed.
interface Graph @0xc662ba0b80ef228b {
  # Creates an edge.
  # AIP-133 standard method.
  createEdge @0 (request :GraphMessages.CreateEdgeRequest) -> (response :Edge.Edge);

  # Retrieves a single edge.
  # AIP-131 standard method.
  getEdge @1 (request :GraphMessages.GetEdgeRequest) -> (response :Edge.Edge);

  # Lists edges.
  # AIP-132 standard method.
  listEdges @2 (request :GraphMessages.ListEdgesRequest) -> (response :GraphMessages.ListEdgesResponse);

  # Creates several edges in one request.
  # AIP-233 standard method.
  batchCreateEdges @3 (request :GraphMessages.BatchCreateEdgesRequest) -> (response :GraphMessages.BatchCreateEdgesResponse);

  # Soft-deletes an edge.
  #
  # Returns the tombstoned edge. Deleting from the graph is reversible until
  # expiry, which matters more here than elsewhere: an edge is often the only
  # record that two things were ever related.
  # AIP-135 standard method.
  deleteEdge @4 (request :GraphMessages.DeleteEdgeRequest) -> (response :Edge.Edge);

  # Traverses the graph outward from a set of seeds.
  #
  # Bounded best-first expansion, not a search over all paths. Each hop depends
  # on the last, so this runs on the host rather than a device, and the bounds
  # — hop count, result ceiling, per-hop decay — are what keep it from becoming
  # the most expensive thing in a query.
  traverseGraph @5 (request :Traversal.TraverseGraphRequest) -> (response :Traversal.TraverseGraphResponse);

  # Creates an edge type, declaring the default weight its edges take.
  # AIP-133 standard method.
  createEdgeType @6 (request :GraphMessages.CreateEdgeTypeRequest) -> (response :Edge.EdgeType);

  # Retrieves a single edge type.
  # AIP-131 standard method.
  getEdgeType @7 (request :GraphMessages.GetEdgeTypeRequest) -> (response :Edge.EdgeType);

  # Lists edge types.
  # AIP-132 standard method.
  listEdgeTypes @8 (request :GraphMessages.ListEdgeTypesRequest) -> (response :GraphMessages.ListEdgeTypesResponse);

  # Soft-deletes an edge type.
  # AIP-135 standard method.
  deleteEdgeType @9 (request :GraphMessages.DeleteEdgeTypeRequest) -> (response :Edge.EdgeType);
}
