@0x8925a387168f6131;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/graph/v1/traversal.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::graph::v1");

# One step along a traversed path.
struct TraversalStep @0xecdca83bf31d1f0e {
  # The edge that was followed.
  edge @0 :Text;
  # The resource this step arrived at.
  resource @1 :Text;
}

# A resource reached by traversal, with the path that reached it.
struct TraversalResult @0xffcac52a0685d317 {
  # The resource that was reached.
  resource @0 :Text;
  # Combined score after applying edge weights and the per-hop decay.
  score @1 :Float32;
  # How many hops from the nearest seed. Zero means the seed itself.
  hopCount @2 :Int32;
  # The path taken, so a result can be cited rather than merely returned.
  #
  # Provenance, not diagnostics: an assembled answer that cannot say how it
  # reached a fact cannot be verified, which for a memory system is most of
  # what it is worth.
  path @3 :List(TraversalStep);
}

# Request message for traversing the graph from a set of seeds.
struct TraverseGraphRequest @0xcca6299cf8d4f1e9 {
  # Organization whose graph is traversed.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Resources to start from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  seeds @1 :List(Text);
  # How many hops to expand. Zero selects a server-chosen default.
  maxHopCount @2 :Int32;
  # Edge types to follow. Empty follows every non-structural type.
  edgeTypes @3 :List(Text);
  # Per-hop score multiplier.
  #
  # Without a decay a node with many neighbours contributes all of them at its
  # own score, and the graph half of a retrieval swamps the similarity half.
  decay @4 :Float32;
  # Ceiling on resources returned, so a hub cannot become the whole answer.
  maxResultCount @5 :Int32;
  # Whether learned traversal strength contributes to the score.
  #
  # Defaults to false, leaving existing behaviour unchanged until asked for.
  # When enabled, an untravelled edge still scores at a prior rather than at
  # zero — otherwise a new edge could never be traversed, so it could never
  # earn a count, and the trap would close on itself.
  useStrength @6 :Bool;
}

# Response message for traversing the graph.
struct TraverseGraphResponse @0x90a0c0d83db1a748 {
  # Resources reached, highest score first.
  results @0 :List(TraversalResult);
  # Edges skipped because they are suppressed.
  #
  # A count, never the edges themselves. The caller assembling context learns
  # that a region was avoided so it can decline to pursue the topic; the person
  # being protected must not be handed the reminder, which is the harm
  # suppression was asked for.
  suppressedEdgeCount @1 :Int32;
  # Whether every part of the graph could be consulted.
  #
  # False when a locked space held part of the path. A caller must be able to
  # tell "nothing is there" from "something is there that you cannot currently
  # see".
  complete @2 :Bool;
  # Spaces skipped because they are locked. Names only, never contents.
  lockedSpaces @3 :List(Text);
}
