// The Points service.
syntax = "proto3";

package episteme.point.v1;

import "episteme/point/v1/point_messages.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";

option java_multiple_files = true;
option java_outer_classname = "PointServiceProto";
option java_package = "dev.episteme.point.v1";

// Manages points within a collection.
service Points {
  option (google.api.default_host) = "episteme.dev";

  // Creates or replaces a batch of points.
  rpc BatchCreatePoints(BatchCreatePointsRequest) returns (BatchCreatePointsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=collections/*}/points:batchCreate"
      body: "*"
    };
  }

  // Retrieves a batch of points by resource name.
  rpc BatchGetPoints(BatchGetPointsRequest) returns (BatchGetPointsResponse) {
    option (google.api.http) = {get: "/v1/{parent=collections/*}/points:batchGet"};
  }

  // Deletes a batch of points.
  rpc BatchDeletePoints(BatchDeletePointsRequest) returns (BatchDeletePointsResponse) {
    option (google.api.http) = {
      post: "/v1/{parent=collections/*}/points:batchDelete"
      body: "*"
    };
  }
}
