@0xc01fb4a56d2c1411;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/point/v1/point_search.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::point::v1");

using Point = import "/telividb/point/v1/point.capnp";

# Why a query cost what it did.
#
# Returned so a slow or surprising result can be explained without reproducing
# it under a profiler.
struct SearchStats @0xbb7f345f4a0d06d5 {
  # Vectors actually scored.
  #
  # Latency tracks this far more closely than it tracks the requested page
  # size.
  candidatesVisited @0 :Int64;
  # Candidates that were rescored at full precision after a coarse scan.
  rerankedCount @1 :Int64;
  # Results drawn from the unsealed write buffer.
  #
  # The buffer is scanned exhaustively, so these are exact. They are reported
  # separately because counting them alongside index results would inflate any
  # recall measurement.
  bufferHitCount @2 :Int32;
  # Results drawn from a sealed segment through its index.
  indexHitCount @3 :Int32;
  # Filter strategy the planner chose, such as `prefilter` or `traversal`.
  filterStrategy @4 :Text;
}

# One point matched by a search, with its score.
struct SearchResult @0xef5ecf7e4f52fa6b {
  # The matching point.
  #
  # Carries the resource itself rather than only its name, so a caller can
  # render a result without a second round trip. Vector fields are omitted
  # unless the read mask asks for them.
  point @0 :Point.Point;
  # Similarity or distance, on the scale of the field's own metric.
  #
  # Whether a higher value is nearer depends on that metric.
  score @1 :Float32;
}

# Request message for searching the points of a collection.
struct SearchPointsRequest @0xb71bef34d8fe51f0 {
  # Collection to search.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier of the vector field to search.
  #
  # Each field has its own model and metric, so a query is meaningful only
  # against the field it was encoded for.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  fieldId @1 :Text;
  # The query vector.
  # The query vector.
  #
  # Optional only because `query_text` is the alternative — a request setting
  # neither is refused. Exactly one of the two must be set.
  query @2 :Point.Vector;
  # Maximum number of results to return.
  #
  # This is the `k` of a nearest-neighbour search, not merely a display limit:
  # it determines how much work the index does. The service may return fewer.
  # Zero selects a server-chosen default.
  pageSize @3 :Int32;
  # Page token from a previous call, to retrieve the following page.
  #
  # Paging beyond the first page re-runs the search with a larger `k`, so a
  # deep page costs more than a shallow one.
  pageToken @4 :Text;
  # Candidate breadth during the search.
  #
  # Larger values improve recall and cost latency on every request. Zero
  # selects a server-chosen default.
  candidateBreadth @5 :Int32;
  # Fields to return for each matched point.
  #
  # Raw vectors are omitted unless explicitly requested, because a vector can
  # be inverted toward its source text — so permission to search is not
  # permission to export.
  readMask @6 :List(Text);
  # Query text for the server to embed.
  #
  # Routed to the field's declared query encoder, which for a joint model is
  # not the same tower that produced the stored vectors: searching an image
  # field with text must encode through the text tower. Getting that wrong
  # returns plausible garbage rather than an error, so the field declares it
  # and the server honours it — a client cannot express the choice and should
  # not have to.
  queryText @7 :Text;
}

# Response message for searching the points of a collection.
struct SearchPointsResponse @0xe0f655b06076c562 {
  # Matching points, nearest first.
  results @0 :List(SearchResult);
  # Token to retrieve the next page, or empty if this is the last page.
  nextPageToken @1 :Text;
  # Whether every source answered.
  #
  # False when a shard missed its deadline or a vault was locked. Present from
  # the first release because a caller must be able to distinguish "no
  # results" from "no results you are currently able to see", and adding it
  # later would break the most-used message in the API.
  complete @2 :Bool;
  # Sources that answered within the deadline.
  answeredSourceCount @3 :Int32;
  # Sources that were consulted.
  totalSourceCount @4 :Int32;
  # Vaults skipped because they are locked.
  #
  # Names only, never contents.
  lockedVaults @5 :List(Text);
  # What the planner did, for explain and for tuning.
  stats @6 :SearchStats;
}
