@0xeb466b6db61dcc78;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/point/v1/point.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::point::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A vector, carried as raw bytes rather than a repeated scalar.
#
# Protobuf encodes a repeated scalar element by element, so a 768-dimension
# vector would cost 768 varint operations per message, in both directions, on
# the hot path. A single length-delimited field costs one.
struct Vector @0xcc924cff72e2d78e {
  # Raw little-endian IEEE-754 single-precision components.
  #
  # Length must equal `dimensions * 4`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  data @0 :Data;
  # Number of components, so a reader can validate before casting.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  dimensions @1 :Int32;
}

# A half-open interval measured from the start of a source.
#
# Present on time-indexed media, because retrieval returns a moment in a
# recording rather than the recording itself.
struct Span @0xd16f19d811959844 {
  # Inclusive start of the interval, relative to the beginning of the source
  # media referenced by the point's content reference.
  #
  # A duration rather than a timestamp: this is a position within the media,
  # not a point in wall-clock time, and the distinction matters when the same
  # recording is ingested twice.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  startOffset @0 :Wellknown.Duration;
  # Exclusive end of the interval, relative to the beginning of the source
  # media referenced by the point's content reference.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  endOffset @1 :Wellknown.Duration;
}

# A pointer to the bytes a point was derived from.
#
# The database stores this rather than the media itself: video is
# gigabyte-scale and blob storage is a solved problem. The digest is what
# detects that a source changed and its embeddings are stale.
struct ContentRef @0xb9382713ca57ccd3 {
  # Location of the source, such as `file://`, `s3://` or `https://`.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  uri @0 :Text;
  # First byte of the range this point covers, when it covers only part.
  rangeStart @1 :Int64;
  # Byte after the range this point covers.
  rangeEnd @2 :Int64;
  # SHA-256 digest of the referenced bytes.
  sha256 @3 :Data;
  # Source text, inlined when small enough to keep the point re-embeddable.
  #
  # Without a reachable source, a collection is locked to the model that
  # created it.
  inlineText @4 :Text;
}

# One vector, keyed by the field it belongs to.
#
# Carries either a vector the caller computed or the text to compute one from.
# Exactly one of `vector` and `text` must be set; both or neither is rejected.
#
# They are separate fields rather than a `oneof` because `vector` already
# shipped outside one, and moving a field into a oneof is a breaking change to
# the message's shape even though the bytes on the wire are unchanged.
struct NamedVector @0x91904ab4c94a54cd {
  # Identifier of the vector field this belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  fieldId @0 :Text;
  # A vector the caller computed.
  #
  # Optional only because `text` is the alternative — a request setting
  # neither is refused.
  vector @1 :Vector;
  # Text for the server to embed into this field.
  #
  # Embedding server-side rather than in the client is the point: one
  # inference server serves ingest, query encoding and plugin compute alike,
  # so the model that produced a field's vectors is a property of the server
  # rather than of whichever client happened to write them. A client with its
  # own model would be a second, unpoliced path to the same field — and mixed
  # provenance inside one index degrades recall with nothing reporting it.
  #
  # The field must be bound to a model the server holds resident; if it is
  # not, the request is refused rather than served by whatever is loaded.
  text @2 :Text;
}

# A single indexed item within a collection.
struct Point @0xd99b0b57f60275a2 {
  # Resource name of the point.
  name @0 :Text;
  # Vectors this point carries, at most one per field.
  #
  # Not every point has every field: a text-only point has no image vector,
  # and that is normal rather than exceptional.
  vectors @1 :List(NamedVector);
  # Interval of the source media this point covers, for time-indexed content.
  span @2 :Span;
  # Reference to the bytes this point was derived from.
  contentRef @3 :ContentRef;
}
