@0xe38ff45795a7c3c1;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/point/v1/point_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::point::v1");

using Point = import "/telividb/point/v1/point.capnp";
using PointMessages = import "/telividb/point/v1/point_messages.capnp";
using PointSearch = import "/telividb/point/v1/point_search.capnp";

# Manages points within a collection.
#
# Every standard method is exposed individually as well as in batch form. A
# caller writing one point should not have to construct a batch, and a caller
# writing a million should not have to send a million requests — the single
# and batch forms share their request message so an SDK can collapse them.
interface Points @0xe780a6144e05db8f {
  # Creates a point.
  # AIP-133 standard method.
  createPoint @0 (request :PointMessages.CreatePointRequest) -> (response :Point.Point);

  # Retrieves a single point.
  # AIP-131 standard method.
  getPoint @1 (request :PointMessages.GetPointRequest) -> (response :Point.Point);

  # Lists the points of a collection.
  # AIP-132 standard method.
  listPoints @2 (request :PointMessages.ListPointsRequest) -> (response :PointMessages.ListPointsResponse);

  # Deletes a point.
  #
  # Returns the tombstoned point rather than an empty message. Deletion here
  # is a soft delete by construction — sealed segments are immutable, so the
  # point is tombstoned and excluded from queries at once while its bytes
  # survive until compaction rewrites the segment. Returning the resource is
  # the form AIP-135 defines for exactly that case, it matches what
  # `BatchDeletePoints` already does, and it leaves room to add fields later
  # that an empty return would have foreclosed.
  # AIP-135 standard method.
  deletePoint @3 (request :PointMessages.DeletePointRequest) -> (response :Point.Point);

  # Creates several points in one request.
  # AIP-233 standard method.
  batchCreatePoints @4 (request :PointMessages.BatchCreatePointsRequest) -> (response :PointMessages.BatchCreatePointsResponse);

  # Retrieves several points in one request.
  # AIP-231 standard method.
  batchGetPoints @5 (request :PointMessages.BatchGetPointsRequest) -> (response :PointMessages.BatchGetPointsResponse);

  # Deletes several points in one request.
  # AIP-235 standard method.
  batchDeletePoints @6 (request :PointMessages.BatchDeletePointsRequest) -> (response :PointMessages.BatchDeletePointsResponse);

  # Searches a collection for the points nearest a query vector.
  #
  # A method on the points collection rather than a service of its own:
  # searching is an operation over points, and modelling it as one keeps the
  # resource hierarchy intact.
  # AIP-136 standard method.
  searchPoints @7 (request :PointSearch.SearchPointsRequest) -> (response :PointSearch.SearchPointsResponse);
}
