@0xdea7772168cc7c16;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/point/v1/point_messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::point::v1");

using Point = import "/telividb/point/v1/point.capnp";

# Request message for creating a point.
struct CreatePointRequest @0xfde6122424c3137f {
  # Collection the point belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use for the point, forming the final path segment.
  pointId @1 :Text;
  # The point to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  point @2 :Point.Point;
}

# Request message for retrieving a point.
struct GetPointRequest @0x9dced38575dd5033 {
  # Resource name of the point to retrieve.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Fields to return.
  #
  # Raw vectors are omitted unless explicitly requested, because a vector can
  # be inverted toward its source text — so permission to read a point is not
  # permission to export it.
  readMask @1 :List(Text);
}

# Request message for listing points.
struct ListPointsRequest @0x8e4fa33cc37dfd02 {
  # Collection to list points from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number of points to return.
  #
  # The service may return fewer. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call, to retrieve the following page.
  pageToken @2 :Text;
  # Fields to return for each point.
  readMask @3 :List(Text);
}

# Response message for listing points.
struct ListPointsResponse @0xaae54b8675e24d92 {
  # The points on this page.
  points @0 :List(Point.Point);
  # Token to retrieve the next page, or empty if this is the last page.
  nextPageToken @1 :Text;
}

# Request message for deleting a point.
struct DeletePointRequest @0x899cd7e4e1043f44 {
  # Resource name of the point to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for creating several points at once.
struct BatchCreatePointsRequest @0x8d4fd171126a9241 {
  # Collection the points belong to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The individual create requests.
  #
  # Each carries a full request rather than a bare point, so a caller can set
  # `point_id` per item and so a single-point client and a batch client build
  # the same message.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  requests @1 :List(CreatePointRequest);
}

# Response message for creating several points at once.
struct BatchCreatePointsResponse @0xe52d18fd041944a3 {
  # The points that were created.
  points @0 :List(Point.Point);
}

# Request message for retrieving several points at once.
struct BatchGetPointsRequest @0xf9e750b67d5b9c4c {
  # Collection the points belong to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Resource names of the points to retrieve.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  names @1 :List(Text);
  # Fields to return for each point.
  readMask @2 :List(Text);
}

# Response message for retrieving several points at once.
struct BatchGetPointsResponse @0x8144396cd6fb3bff {
  # The points that were found, in the order requested.
  points @0 :List(Point.Point);
}

# Request message for deleting several points at once.
struct BatchDeletePointsRequest @0x93b4793ad99351df {
  # Collection the points belong to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Resource names of the points to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  names @1 :List(Text);
}

# Response message for deleting several points at once.
struct BatchDeletePointsResponse @0xa6d64ba902f73561 {
  # The points that were tombstoned.
  #
  # Deletion writes a tombstone; the stored bytes survive until a segment is
  # rewritten by compaction. A caller needing erasure rather than concealment
  # must force compaction and confirm it completed.
  points @0 :List(Point.Point);
}
