@0x8719131e825ba9be;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/connector/v1/connector_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::mcp::v1");

using Connector = import "/telividb/connector/v1/connector.capnp";

# Request message for registering an MCP server.
struct CreateMcpServerRequest @0xb3f8efa650c3a548 {
  # Organization the registration belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  mcpServerId @1 :Text;
  # The server to register.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  mcpServer @2 :Connector.McpServer;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a registered MCP server.
struct GetMcpServerRequest @0xec34714ec45bc1d7 {
  # Resource name of the server.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing registered MCP servers.
struct ListMcpServersRequest @0xdd213a13ffc7bcce {
  # Organization to list servers from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression, such as `embed_results = true`.
  filter @3 :Text;
  # Whether to include soft-deleted registrations.
  showDeleted @4 :Bool;
}

# Response message for listing registered MCP servers.
struct ListMcpServersResponse @0x9afbc4073bd6ed73 {
  # The servers on this page.
  mcpServers @0 :List(Connector.McpServer);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a registered MCP server.
struct DeleteMcpServerRequest @0xc90ff6a99f0629ed {
  # Resource name of the server to deregister.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for introspecting an MCP server's capabilities.
struct IntrospectMcpServerRequest @0x9710fbc5e15c5b06 {
  # Resource name of the server to introspect.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Response message for introspecting an MCP server.
struct IntrospectMcpServerResponse @0xccd97b526b099404 {
  # Tools the server exposes, carried verbatim.
  tools @0 :List(Connector.McpTool);
  # Digest of this capability set.
  capabilityDigest @1 :Text;
  # Whether the capability set changed since the last introspection.
  #
  # Drift pauses a sync rather than proceeding without the changed field.
  # Silently dropping a field is the failure with no symptom.
  drifted @2 :Bool;
}

# Manages the MCP servers this deployment may call.
interface McpServers @0xbe0a9a9fd8727a10 {
  # Registers an MCP server.
  # AIP-133 standard method.
  createMcpServer @0 (request :CreateMcpServerRequest) -> (response :Connector.McpServer);

  # Retrieves a single registration.
  # AIP-131 standard method.
  getMcpServer @1 (request :GetMcpServerRequest) -> (response :Connector.McpServer);

  # Lists registered servers.
  # AIP-132 standard method.
  listMcpServers @2 (request :ListMcpServersRequest) -> (response :ListMcpServersResponse);

  # Connects and enumerates what the server exposes.
  #
  # Reports the raw capability set. No model is involved and nothing is
  # applied: the text here is written by whoever runs that server, so feeding
  # it to something that decides what to embed would be a prompt-injection
  # surface where the injected instruction acts on this deployment's data.
  introspectMcpServer @3 (request :IntrospectMcpServerRequest) -> (response :IntrospectMcpServerResponse);

  # Soft-deletes a registration.
  # AIP-135 standard method.
  deleteMcpServer @4 (request :DeleteMcpServerRequest) -> (response :Connector.McpServer);
}
