@0xae391cdeedda00a8;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/context/v1/context_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::context::v1");

using ContextTemplate = import "/telividb/context/v1/context_template.capnp";

# Request message for creating a context template.
struct CreateContextTemplateRequest @0xe89625e4238bd618 {
  # Organization the template belongs to.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Identifier to use, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  contextTemplateId @1 :Text;
  # The template to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  contextTemplate @2 :ContextTemplate.ContextTemplate;
  # Unique identifier making this request safe to retry.
  requestId @3 :Text;
}

# Request message for retrieving a context template.
struct GetContextTemplateRequest @0xdede7e1e567946ca {
  # Resource name of the template.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing context templates.
struct ListContextTemplatesRequest @0xfcf2265385482b35 {
  # Organization to list templates from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum number to return. Zero selects a server-chosen default.
  pageSize @1 :Int32;
  # Page token from a previous call.
  pageToken @2 :Text;
  # Filter expression restricting which templates are returned.
  filter @3 :Text;
}

# Response message for listing context templates.
struct ListContextTemplatesResponse @0x9471daa6f1764b63 {
  # The templates on this page.
  contextTemplates @0 :List(ContextTemplate.ContextTemplate);
  # Token to retrieve the next page, or empty if this is the last.
  nextPageToken @1 :Text;
}

# Request message for deleting a context template.
struct DeleteContextTemplateRequest @0xcca3db594cf0c9b8 {
  # Resource name of the template to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
  # Current etag, to refuse a delete racing a concurrent change.
  etag @1 :Text;
}

# Request message for assembling context.
struct AssembleContextRequest @0xa7f3952a2b6b7cc0 {
  # Organization to retrieve from.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # What to retrieve for.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  query @1 :Text;
  # Restrict retrieval to these spaces. Empty searches everything visible.
  spaces @2 :List(Text);
  # A saved template supplying expansion and budget.
  contextTemplate @3 :Text;
  # Expansion settings, overriding the template.
  expansion @4 :ContextTemplate.Expansion;
  # Budget, overriding the template.
  budget @5 :ContextTemplate.Budget;
}

# Response message for assembling context.
struct AssembleContextResponse @0xeafe199a8bc7a989 {
  # The fragments, highest score first.
  fragments @0 :List(ContextTemplate.Fragment);
  # Whether every source could be consulted.
  complete @1 :Bool;
  # Spaces skipped because they are locked. Names only, never contents.
  lockedSpaces @2 :List(Text);
  # Whether a suppressed region borders these results.
  #
  # Machine-visible and human-invisible. A caller that reasons over this can
  # decline to pursue the topic; the rendered answer must never say that a
  # suppressed memory exists, because delivering that reminder is the harm
  # suppression was asked for.
  suppressedRegionAdjacent @3 :Bool;
}

# Manages context templates and assembles retrieval context from them.
#
# Named for the resource it manages rather than for the operation, which is
# both what AIP-121 asks and what avoids a real collision: a service called
# `Context` generates a trait called `Context`, and that shadows
# `std::task::Context` inside the generated service code.
#
# The boundary is deliberate: this returns ranked, deduplicated,
# budget-fitted fragments with provenance. It does not render a prompt and does
# not call a generative model. The moment the engine templates prompts it is
# coupled to one model's chat format, and the database would need re-releasing
# every time a template changed.
interface ContextTemplates @0xe126b7a7078b0ef2 {
  # Creates a context template.
  # AIP-133 standard method.
  createContextTemplate @0 (request :CreateContextTemplateRequest) -> (response :ContextTemplate.ContextTemplate);

  # Retrieves a single context template.
  # AIP-131 standard method.
  getContextTemplate @1 (request :GetContextTemplateRequest) -> (response :ContextTemplate.ContextTemplate);

  # Lists context templates.
  # AIP-132 standard method.
  listContextTemplates @2 (request :ListContextTemplatesRequest) -> (response :ListContextTemplatesResponse);

  # Soft-deletes a context template.
  # AIP-135 standard method.
  deleteContextTemplate @3 (request :DeleteContextTemplateRequest) -> (response :ContextTemplate.ContextTemplate);

  # Searches, expands along the graph, deduplicates, ranks and fits a budget.
  #
  # Unary rather than streaming. Streaming would change the ranking contract:
  # you cannot re-rank what has already been sent, and the whole value here is
  # that the ordering accounts for everything retrieved.
  assembleContext @4 (request :AssembleContextRequest) -> (response :AssembleContextResponse);
}
