@0xca501a6ad64d8ed2;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/context/v1/context_template.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::context::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A saved retrieval configuration.
#
# A resource rather than a set of request parameters, because it is also an
# authorization surface: the person who saves a template and the person who
# runs it may see different rows. Policy is therefore evaluated at run time
# against the caller, never at save time against the author — otherwise a
# saved template becomes a way to read rows you could not query for directly.
struct ContextTemplate @0xa871e8d0e2203d44 {
  # Resource name of the template.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # How far to expand along the graph.
  expansion @2 :Expansion;
  # Ceiling on what may be returned.
  budget @3 :Budget;
  # When the template was created.
  createTime @4 :Wellknown.Timestamp;
  # When the template was last modified.
  updateTime @5 :Wellknown.Timestamp;
  # When the template was soft-deleted, or unset while live.
  deleteTime @6 :Wellknown.Timestamp;
  # When a soft-deleted template is purged and becomes unrecoverable.
  expireTime @7 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @8 :Text;
}

# How far a retrieval expands from its similarity seeds.
struct Expansion @0xc685b2b7bc596149 {
  # Hops to follow. Zero disables expansion and returns pure similarity.
  maxHopCount @0 :Int32;
  # Edge types to follow. Empty follows every non-structural type.
  edgeTypes @1 :List(Text);
  # Per-hop score multiplier.
  decay @2 :Float32;
  # Ceiling on expanded results, so a hub cannot become the whole answer.
  maxExpandedCount @3 :Int32;
  # Whether learned traversal strength contributes to ranking.
  useStrength @4 :Bool;
  # Whether to search the summary tier before the message tier.
  #
  # Coarse-to-fine: summaries narrow the field, then expansion descends into
  # the messages they cover. The same shape the vector path already uses when
  # a quantized scan precedes a full-precision rerank.
  useSummaries @5 :Bool;
}

# A ceiling on what an assembly may return.
struct Budget @0x995cd8c00aba6dc3 {
  # Maximum fragments to return.
  maxFragmentCount @0 :Int32;
  # Approximate token ceiling across all fragments.
  maxTokenCount @1 :Int32;
}

# One retrieved piece of context, with the path that reached it.
struct Fragment @0xc92ae895b1bf07da {
  # The resource this came from.
  source @0 :Text;
  # The text.
  content @1 :Text;
  # Combined score after similarity, decay, weights and recency.
  score @2 :Float32;
  # Hops from the nearest seed. Zero means a direct similarity match.
  hopCount @3 :Int32;
  # The seed this was reached from.
  reachedVia @4 :Text;
  # Whether this fragment is a summary rather than stored content.
  summarized @5 :Bool;
  # The MCP server this originated with, when it came from a tool result.
  #
  # Provenance carried through to the point of use: text a third-party server
  # returned must not rank as memory the same way something a person said
  # does, and a caller cannot make that distinction without being told.
  mcpServer @6 :Text;
}
