@0xb5187cb879aa7b7b;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/mcp/v1/mcp_server.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::mcp::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A registered MCP server this deployment may call tools on.
#
# Consuming an MCP server is an ordinary source, not a parallel ingest path: it
# emits the same record stream bulk import already consumes, inheriting jobs,
# checkpoints, resume and reject files rather than growing failure machinery of
# its own.
struct McpServer @0xd06586e020b4f052 {
  # Resource name of the server.
  name @0 :Text;
  # Human-readable name.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  displayName @1 :Text;
  # Where to reach the server.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  endpoint @2 :Text;
  # Whether results from this server may be embedded into the index.
  #
  # False unless an operator sets it deliberately, and that default is the
  # security boundary rather than a convenience. Text a server returns is
  # written by whoever runs that server; embedding it makes it retrievable
  # memory that a later context assembly can pull into a window, where it
  # steers the agent. Unlike a one-time schema review, that recurs on every
  # call and persists.
  #
  # Nothing infers this. A classifier may propose the change and may never
  # apply it — automatic movement is permitted only toward withholding.
  embedResults @3 :Bool;
  # Digest of the capability set last introspected from this server.
  #
  # A source that silently gains or changes a tool is how ingest starts
  # dropping data or accepting something it was never reviewed for. Comparing
  # this is what detects drift.
  capabilityDigest @4 :Text;
  # When the server was last introspected.
  introspectTime @5 :Wellknown.Timestamp;
  # When the server was registered.
  createTime @6 :Wellknown.Timestamp;
  # When the registration was last modified.
  updateTime @7 :Wellknown.Timestamp;
  # When the registration was soft-deleted, or unset while it is live.
  deleteTime @8 :Wellknown.Timestamp;
  # When a soft-deleted registration is purged and becomes unrecoverable.
  expireTime @9 :Wellknown.Timestamp;
  # Opaque value for optimistic concurrency on update.
  etag @10 :Text;
}

# One tool a server exposes.
struct McpTool @0xc49eea39fc3b426b {
  # Name the server gives this tool.
  #
  # Attacker-controlled text: written by whoever runs the server, never by this
  # deployment. It is displayed and filtered on, and it is never fed to a model
  # that decides what to embed.
  tool @0 :Text;
  # Description the server supplies, carried verbatim.
  description @1 :Text;
  # JSON Schema for the tool's input, as the server published it.
  inputSchema @2 :Text;
}
