@0xe7bf7188ae764e6b;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: buffers/wellknown.capnp
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("buffers::wellknown");

# Timestamp is google.protobuf.Timestamp: seconds since the Unix epoch plus a
# nanosecond adjustment.
struct Timestamp @0xd4efd046929394b8 {
  seconds @0 :Int64;
  nanos @1 :Int32;
}

# Duration is google.protobuf.Duration: a signed span.
struct Duration @0xa744efa44d2e99a1 {
  seconds @0 :Int64;
  nanos @1 :Int32;
}
