@0xdc1dfad98742b3ce;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/models/v1/catalog_model.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::models::v1");

# What a model turns into vectors.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Modality @0x9079857bce6683e4 {
  # Unspecified. Never returned by the server.
  unspecified @0;
  # Natural-language text, and the only modality with an encoder behind it.
  text @1;
  # Still images. No loadable architecture yet.
  image @2;
  # Speech or general audio. No loadable architecture yet.
  audio @3;
  # Video. No loadable architecture yet.
  video @4;
}

# A model the server offers to install, verified against the file it names.
#
# Curated rather than searched. The encoder implements a fixed set of GGUF
# architectures, and model hosts carry tens of thousands of files that are
# mostly generative models it cannot read — so a search would mostly return
# downloads that fail. Every field here was read from the actual file or from
# the host's API, never copied from a model card.
struct CatalogModel @0x99279b04238057b3 {
  # Resource name of the catalog model.
  name @0 :Text;
  # Name shown to a person choosing.
  displayName @1 :Text;
  # What this model is good for, in terms someone can act on.
  #
  # Bigger is not simply better: width costs index size and query latency, so
  # the description says what the trade buys.
  description @2 :Text;
  # Page for these weights, for checking licence and provenance at the source.
  repositoryUri @3 :Text;
  # SHA-256 of the model file, as sixty-four lowercase hex characters.
  #
  # The identity, not the label. Two files under one name produce different
  # vectors, and mixing them into one index degrades recall with nothing
  # reporting it. Verified after download; a mismatch is refused.
  digest @4 :Text;
  # Exact size of the file in bytes.
  #
  # Exact rather than rounded, because a progress indicator divides by it.
  sizeBytes @5 :Int64;
  # What this model embeds.
  modality @6 :Modality;
  # GGUF architecture, read from the file's own header.
  architecture @7 :Text;
  # Components in the vectors it produces.
  #
  # A vector field bound to this model must declare the same width.
  dimensions @8 :Int32;
  # Maximum input length in tokens; longer input is truncated.
  contextLength @9 :Int32;
  # Quantization the file carries, such as `Q8_0`.
  quantization @10 :Text;
  # SPDX identifier for the weights' licence.
  license @11 :Text;
  # Whether this is the default offer for a caller with no preference.
  #
  # Exactly one catalog model sets this. Two defaults is a choice presented as
  # a recommendation, which leaves the caller no better off.
  recommended @12 :Bool;
  # Whether the file is present locally and matches its digest.
  installed @13 :Bool;
}
