@0xf1d9ef47043d9418;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/models/v1/model_installation.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::models::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# How far an installation has got.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InstallationState @0xb2739d420cc08c64 {
  # Unspecified. Never returned by the server.
  unspecified @0;
  # Accepted and waiting to start.
  pending @1;
  # Transferring bytes.
  downloading @2;
  # Transferred; the digest is being checked against the catalog.
  verifying @3;
  # Installed, verified, and ready once the engine next starts.
  succeeded @4;
  # Stopped without installing. `error` says why.
  failed @5;
  # Cancelled by a caller deleting the installation.
  cancelled @6;
}

# One attempt to install a catalog model.
#
# A resource rather than a blocking call, because a model file is hundreds of
# megabytes: an install outlives any request deadline, has to survive a restart,
# and has to be cancellable. Creating this returns immediately with a handle;
# progress is read back by getting it.
struct ModelInstallation @0xe3f3a0cb57f40354 {
  # Resource name of the installation.
  name @0 :Text;
  # The catalog model being installed.
  catalogModel @1 :Text;
  # How far it has got.
  state @2 :InstallationState;
  # Bytes written so far, including any resumed from an earlier attempt.
  #
  # Cumulative rather than per-attempt, so a resumed install shows a bar that
  # continues instead of restarting.
  progressBytes @3 :Int64;
  # Total bytes expected, copied from the catalog entry.
  totalBytes @4 :Int64;
  # Why it failed, when `state` is `FAILED`.
  #
  # A digest mismatch is reported here rather than as a transport error: the
  # file arrived intact and is not the file the catalog names, which is a
  # different problem with a different remedy.
  error @5 :Text;
  # When the installation was created.
  createTime @6 :Wellknown.Timestamp;
  # When its state last changed.
  updateTime @7 :Wellknown.Timestamp;
}
