@0x9bda45a82652b072;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/models/v1/models_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::models::v1");

using CatalogModel = import "/telividb/models/v1/catalog_model.capnp";
using ModelInstallation = import "/telividb/models/v1/model_installation.capnp";

# Request message for listing catalog models.
struct ListCatalogModelsRequest @0x82e5ab77e4e14983 {
  # Maximum number to return. The server may return fewer.
  pageSize @0 :Int32;
  # Page token from a previous response.
  pageToken @1 :Text;
  # Restricts the results, using the standard filter grammar.
  #
  # `modality = "text"` is the one worth knowing: every other modality is
  # empty today, because no encoder exists for it.
  filter @2 :Text;
}

# Response message for listing catalog models.
struct ListCatalogModelsResponse @0xb7fe499bcae8a11d {
  # The models on offer, in catalog order.
  catalogModels @0 :List(CatalogModel.CatalogModel);
  # Token for the next page, empty when there are no more.
  nextPageToken @1 :Text;
}

# Request message for retrieving a catalog model.
struct GetCatalogModelRequest @0xa938320703e11680 {
  # Resource name of the catalog model.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for starting an installation.
struct CreateModelInstallationRequest @0x9cf07568a5ba8b38 {
  # The installation to create. Only `catalog_model` is read.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  modelInstallation @0 :ModelInstallation.ModelInstallation;
  # Client-chosen identifier for the installation.
  #
  # Supplying one makes the call idempotent: repeating it returns the existing
  # installation rather than starting a second transfer of the same file.
  modelInstallationId @1 :Text;
}

# Request message for retrieving an installation.
struct GetModelInstallationRequest @0xbb6ff72e907ddf27 {
  # Resource name of the installation.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing installations.
struct ListModelInstallationsRequest @0xc296745e11cda113 {
  # Maximum number to return. The server may return fewer.
  pageSize @0 :Int32;
  # Page token from a previous response.
  pageToken @1 :Text;
}

# Response message for listing installations.
struct ListModelInstallationsResponse @0xaa2e518caf3856ff {
  # The installations, most recent first.
  modelInstallations @0 :List(ModelInstallation.ModelInstallation);
  # Token for the next page, empty when there are no more.
  nextPageToken @1 :Text;
}

# Request message for cancelling or forgetting an installation.
struct DeleteModelInstallationRequest @0xb193687022bd50fe {
  # Resource name of the installation.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Offers a curated set of embedding models, and installs them.
#
# Separate from `telividb.inference.v1`, which is about models already resident
# and the vectors they produce. This is about acquiring the files: what is on
# offer, what is present locally, and how far a download has got.
#
# Curated rather than searchable. The encoder implements a fixed set of GGUF
# architectures, and a model host carries tens of thousands of files that are
# mostly generative models it cannot read — so a search would mostly return
# downloads that fail after several hundred megabytes.
interface Models @0xe82732224215fe68 {
  # Lists the models on offer.
  # AIP-132 standard method.
  listCatalogModels @0 (request :ListCatalogModelsRequest) -> (response :ListCatalogModelsResponse);

  # Retrieves one catalog model.
  # AIP-131 standard method.
  getCatalogModel @1 (request :GetCatalogModelRequest) -> (response :CatalogModel.CatalogModel);

  # Starts installing a catalog model.
  #
  # Returns as soon as the work is accepted, not when it finishes. A model file
  # is hundreds of megabytes, so the transfer outlives any request deadline;
  # poll the returned installation to follow it.
  #
  # Installing something already present and intact succeeds immediately
  # without transferring anything.
  # AIP-133 standard method.
  createModelInstallation @2 (request :CreateModelInstallationRequest) -> (response :ModelInstallation.ModelInstallation);

  # Retrieves an installation, with its progress.
  # AIP-131 standard method.
  getModelInstallation @3 (request :GetModelInstallationRequest) -> (response :ModelInstallation.ModelInstallation);

  # Lists installations, most recent first.
  # AIP-132 standard method.
  listModelInstallations @4 (request :ListModelInstallationsRequest) -> (response :ListModelInstallationsResponse);

  # Cancels an installation, or forgets a finished one.
  #
  # Cancelling leaves the partial file in place, so installing again resumes
  # rather than starting over.
  # AIP-135 standard method.
  deleteModelInstallation @5 (request :DeleteModelInstallationRequest) -> (response :ModelInstallation.ModelInstallation);
}
