@0x9567603b6af4045c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/collection/v1/collection.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::collection::v1");

# How similarity is measured within a named vector field.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Metric @0xbc1927ab7ce9715d {
  # Default value. Never valid in a request.
  unspecified @0;
  # Inner product. A higher score is nearer.
  dot @1;
  # Squared Euclidean distance. A lower score is nearer.
  l2 @2;
  # Angular similarity. Normalized at ingest and scored as dot thereafter.
  cosine @3;
}

# Compression applied to a field's coarse scan tier.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Codec @0xb6a145e2712ed95f {
  # Default value. Never valid in a request.
  unspecified @0;
  # No scan tier. Searches read full precision directly.
  none @1;
  # Half precision. Two bytes per component, effectively lossless for ranking.
  f16 @2;
  # Scalar quantization with a per-row scale and offset.
  int8 @3;
  # Product quantization. One byte per subspace.
  pq @4;
  # One bit per component. Coarse enough to require a rerank.
  binary @5;
}

# Which search algorithm indexes a field.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum IndexKind @0x8597645dbed6f5ee {
  # Default value. Never valid in a request.
  unspecified @0;
  # Exhaustive search. Ground truth, and correct for small fields.
  flat @1;
  # Hierarchical navigable small world graph.
  hnsw @2;
  # Inverted file with product quantization, for memory-constrained fields.
  ivfPq @3;
}

# One named vector field within a collection.
#
# A collection may declare several, each with its own model, dimension and
# metric — which is what makes a single collection multimodal.
struct VectorField @0xd9dcc01ecbe7b2e2 {
  # Identifier of the field, such as `image_clip`. Unique within its
  # collection.
  #
  # Named `field_id` rather than `name` because a vector field is a component
  # of a collection, not a resource of its own — it has no resource name and
  # cannot be addressed directly.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  fieldId @0 :Text;
  # Number of components in every vector of this field.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  dimensions @1 :Int32;
  # How similarity is measured.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  metric @2 :Metric;
  # Which search algorithm indexes this field.
  indexKind @3 :IndexKind;
  # Compression applied to the coarse scan tier.
  codec @4 :Codec;
  # Identifier of the model that produces vectors for this field.
  model @5 :Text;
  # Encoder that handles queries against this field.
  #
  # For a jointly trained model this is the other tower: searching an image
  # field with text must encode that text with the model's text encoder.
  # Declared rather than left to convention, because getting it wrong yields
  # plausible but incorrect results rather than an error.
  queryEncoder @6 :Text;
  # Permission controlling access to raw vectors of this field.
  #
  # Per field rather than per collection, because a voiceprint is biometric
  # data where a transcript is not.
  permission @7 :Text;
}

# A set of points sharing one schema, one identity space and one set of
# vector fields.
struct Collection @0x9e6e6addc8ac4f26 {
  # Resource name of the collection, such as `collections/media`.
  name @0 :Text;
  # Serialized `FileDescriptorSet` describing this collection's schema.
  #
  # The engine never parses `.proto`. A generator produces this and it is
  # stored verbatim as the schema of record.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  descriptorSet @1 :Data;
  # Digest of the canonicalized descriptor set, mirrored into every segment
  # written under it.
  schemaFingerprint @2 :Data;
  # Named vector fields this collection holds.
  vectorFields @3 :List(VectorField);
  # Points currently visible to readers.
  livePointCount @4 :Int64;
  # Points deleted but not yet reclaimed by compaction.
  tombstonedPointCount @5 :Int64;
  # Sealed segments making up this collection.
  segmentCount @6 :Int32;
}
