@0xe9dbb80c580980ad;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/collection/v1/collection_messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::collection::v1");

using Collection = import "/telividb/collection/v1/collection.capnp";

# Request message for creating a collection.
struct CreateCollectionRequest @0xb7f1601ccf005bc2 {
  # Identifier to use for the collection, forming the final path segment.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  collectionId @0 :Text;
  # The collection to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  collection @1 :Collection.Collection;
}

# Request message for retrieving a collection.
struct GetCollectionRequest @0x9d64283425dbf1c5 {
  # Resource name of the collection to retrieve.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for listing collections.
struct ListCollectionsRequest @0xf6e3600ef7fb1ceb {
  # Maximum number of collections to return.
  #
  # The service may return fewer. Zero selects a server-chosen default.
  pageSize @0 :Int32;
  # Page token from a previous call, to retrieve the following page.
  pageToken @1 :Text;
}

# Response message for listing collections.
struct ListCollectionsResponse @0xbbb3e245de86fa6a {
  # The collections on this page.
  collections @0 :List(Collection.Collection);
  # Token to retrieve the next page, or empty if this is the last page.
  nextPageToken @1 :Text;
}

# Request message for deleting a collection.
struct DeleteCollectionRequest @0x974876fdf59df30f {
  # Resource name of the collection to delete.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
