@0xcd748333f1ac3721;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: telividb/collection/v1/collection_service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("telividb::collection::v1");

using Collection = import "/telividb/collection/v1/collection.capnp";
using CollectionMessages = import "/telividb/collection/v1/collection_messages.capnp";

# Manages collections and their schemas.
interface Collections @0x8c62ff72cabb34ae {
  # Creates a collection from a compiled schema descriptor set.
  # AIP-133 standard method.
  createCollection @0 (request :CollectionMessages.CreateCollectionRequest) -> (response :Collection.Collection);

  # Retrieves a single collection.
  # AIP-131 standard method.
  getCollection @1 (request :CollectionMessages.GetCollectionRequest) -> (response :Collection.Collection);

  # Lists collections.
  # AIP-132 standard method.
  listCollections @2 (request :CollectionMessages.ListCollectionsRequest) -> (response :CollectionMessages.ListCollectionsResponse);

  # Deletes a collection and every segment belonging to it.
  #
  # Returns the tombstoned collection. The collection stops answering queries
  # immediately; reclaiming the segments is a checkpointed job, because
  # deleting every segment is unbounded work that cannot fit in a deadline.
  # AIP-135 standard method.
  deleteCollection @3 (request :CollectionMessages.DeleteCollectionRequest) -> (response :Collection.Collection);
}
